### ISSUE TITLE
Devices not updating after edit

### ISSUE THREAD

**Issue by mrstacey1284** [Colorado4Wheeler/HomeKit-Bridge#100]
After editing a device on HomeKit Bridge Server in indigo it is not updated in Home.app. For instance during initial setup I accidentally chose alarm for what should have been a motion detector. When I tried to change it to a motion detector it remains represented as an alarm in Home.app. I have tried restarting the server, force closing the app, and setting up a new home to be able to switch back and forth. Is there anything that can be done other then removing the whole hub accessory and starting over?

**Comment by Colorado4Wheeler** [comment]
I've never seen or heard of this happening and from a programming standpoint I'm not sure how it could.  The device is defined in real-time each time Homebridge reaches out to Indigo and whatever is shown during that conversation is what the device shows up as unless you are changing it from within HomeKit itself (which is possible).

Removing the accessory won't change anything, but what you can do is delete the **device** in your HomeKit Bridge accessory and re-add it, this should force Homebridge to see it as a new device because the ID will change.

**Comment by mrstacey1284** [comment]
Following the advice above has exposed another issue I am experiencing. I can not delete devices from the HomeKit Bridge Accessory. No matter which of the three delete options I chose nothing happens and the following error appears in the log:

`  HomeKit Bridge Error            Exception in plugin.serverButtonRunAction line 3355: invalid literal for int() with base 10: 'c7db68051460ef1748de9496a3412f212f11ac03773a03a51c4563c81bd9c2d2'
							 CODE: includedDevices = eps.jstash.removeRecordFromStash (includedDevices, "id", int(id))`

**Comment by Colorado4Wheeler** [comment]
Please upgrade your version, this was fixed several releases ago.

**Comment by mrstacey1284** [comment]
I am currently using version v0.22.2, Is that not the most recent version?

Also, having major issue with status of devices not staying updated properly. For instance, I will lock the door through home.app, it will physically lock the door, but the status will continue to read updating until the home.app is reloaded. At that point it will read unlocked despite being locked.

**Comment by Colorado4Wheeler** [comment]
Version 23.1 is the most recent version :).  You can always check that [by looking at the releases for the plugin](https://github.com/Colorado4Wheeler/HomeKit-Bridge/releases), but that error was dealt with already so if you upgrade then you can delete again.

As for your lock can you please use the advanced plugin actions -> select your server -> simulate -> select your device -> copy and paste the output to here so I can see what your lock looks like.  I suspect it's a plugin that is not yet directly supported as there have been no issues of standard Zwave locks not working.
