### ISSUE TITLE
Initial test of HKB only turns light on not off

### ISSUE THREAD

**Issue by tcherna** [Colorado4Wheeler/HomeKit-Bridge#103]
Just hit what looks like the same condition that spiv described on 4/7.

Homekit can turn my switch on, but not off.   Homekit shows that the device is off, indigo doesn't show any logs for HKB.

##### DEVICE DATA DUMP #####
	
	address : 3C.35.75
	batteryLevel : None
	buttonGroupCount : 1
	configured : True
	description : 
	deviceTypeId : 
	displayStateId : onOffState
	displayStateImageSel : PowerOn
	displayStateValRaw : True
	displayStateValUi : on
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 0
	globalProps : MetaProps : (dict)
	id : 1137988370
	lastChanged : 2018-04-14 23:04:59
	lastSuccessfulComm : 2018-04-14 23:04:59
	ledStates : []
	model : SwitchLinc Relay
	name : Master Bedroom (S)
	onState : True
	ownerProps : emptyDict : (dict)
	pluginId : 
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Insteon
	remoteDisplay : True
	states : States : (dict)
	     onOffState : on (on/off bool)
	subModel : 
	supportsAllLightsOnOff : True
	supportsAllOff : True
	supportsStatusRequest : True
	version : 69
	
	##### DEVICE SIMULATION DATA #####
	
	Service : 
		alias : Master Bedroom (S)
		model : 
		subModel : 
		indigoType : indigo.RelayDevice
		pluginType : Built-In
		type : Lightbulb
		desc : Lightbulb
		objId : 1137988370
		serverId : 1021198396
		invertOnState : False
		convertFahrenheit : False
		required : (List)
			On : True
		optional : (List)
			Hue
			Saturation
			ColorTemperature
			Name
			Brightness
		native : True
		requiresPlugin : (List)
		actions : (List)
			Action : (HomeKitAction)
				Characteristic : On
				When : equal
				Value : False (bool)
				Value2 : 0 (bool)
				Command : device.turnOff
				Arguments : [1137988370]
				monitors : {1137988370: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : On
				When : equal
				Value : True (bool)
				Value2 : 0 (bool)
				Command : device.turnOn
				Arguments : [1137988370]
				monitors : {1137988370: 'attr_onState'}
		loadOptional : False
		characterDict : (Dict)
			On : True

**Comment by tcherna** [comment]
hmm.  I removed the device and the accessory from HomeKit and readded and now it seems to work

**Comment by Colorado4Wheeler** [comment]
What are you doing or trying to do when you get that error?

**Comment by tcherna** [comment]
I have the one switch added to the HKB and one accessory added in HomeKit.   I’m just toggling the light from the Home app. 

I don’t see that error each time.  In fact I didn’t see it when I had the original response issue.  

tdc

**Comment by Colorado4Wheeler** [comment]
I don’t think it’s a “bug” per se because the nature of that call would mean that if it were a deep rooted bug that you would get it every time, and so would everyone else because that is currently called each time you do anything in HomeKit with a device.  That leads me to believe it could be how the device was configured or perhaps it only is coming up under a certain circumstance, like before the plugin was restarted the first time after adding the new server in Indigo.

If it’s not happening regularly then it’ll be impossible to give you any advice as to what you can do.  If you can keep an eye on it and try to determine when it happens that will help.

**Comment by tcherna** [comment]
I’m still seeing it.  It happens on each message from HomeKit to the server when I toggle the light.  Happy to debug further if you have ideas.

tdc

**Comment by Colorado4Wheeler** [comment]
Try editing the device on the server and change the alias name to something else and see if that does anything.  The message implies that there is no alias name, which is kind of strange.

**Comment by tcherna** [comment]
Interesting, if I rename the device, delete the bridge from HomeKit, and re-add it, it still comes up with the old name, in fact even if the device has been deleted from the bridge, it still can be seen by HomeKit.

Is there a way to get it to refresh the HomeKit list without deleting and re-adding the accessory

**Comment by Colorado4Wheeler** [comment]
Rename the device and delete the bridge and what comes back as the same name - the accessory server or the device itself?  I would delete the accessory server from HomeKit, rename the server device to something new and change the alias name of any items that are mapped and see what that does.

**Comment by tcherna** [comment]
Right now, I’m actually not able to re-add the accessory (server) in HomeKit.  But I’ll try renaming that too.

However, the problem may because I did create an alias for my device.  Maybe it would be easier if the indigo name and the HomeKit name matched?

I did the following:

Delete the HomeKit bridge device.
Added a new HomeKit bridge device (new name)
Added the same switch, with an alias
Added to the Home app (now it showed up)
No more error logs, and the light works.

Its complicated because there are so many names for the various parts in each world.  I can keep watching for stuff though (I’m a Mac developer, so should be a bit handy ;) )

I did have an insteon related question if you know, though.  Some of my lights are connected to keypads — and from past reading, a good workflow to keep them in sync was to use an insteon scene to turn both the light / keypad on off, and I use a python script when I toggle those from the indigo control page.

Of course, with home kit, now the keypad is out of sync.  Do you think one can make a HomeKit device talk to the scene?  I’m imagining using an action script to toggle that, but I’m not quite sure how HomeKit would get the status of the device.

Otherwise, I can have a watch / trigger rule in indigo, but those never work so well.

Thanks!  This is very impressive.

**Comment by Colorado4Wheeler** [comment]
> Maybe it would be easier if the indigo name and the HomeKit name matched?

I'm not sure what you are asking because there is the Indigo Server Accessory Device that equates to the HomeKit Accessory and then there are the Indigo devices that are mapped to HomeKit.  For me, for over 200 devices almost none of them have the same name as Indigo's device names.

> Otherwise, I can have a watch / trigger rule in indigo, but those never work so well.

That's the only way to really do that.  I also use KPL's and I have a trigger that detects when a light goes on or off and then runs a Py script to update all linked KPL's.  It works 100% for me, not sure why your triggers don't work very well but they work perfectly for me.

**Comment by Colorado4Wheeler** [comment]
Since there has been no further information on this ticket I'm assuming it's not an issue and closed.
