### ISSUE TITLE
Garage Door Device shows wrong Closed/Open Status

### ISSUE THREAD

**Issue by grwilde** [Colorado4Wheeler/HomeKit-Bridge#104]
### Current Behavior

The problem I see is that the Garage Door reports open when closed and closed when open regardless of whether I set the Invert Open/Closed status or not.  Shows the wrong Garage Door Open/Closed status regardless of the setting of Invert On/Off State. The previous versions did not have this problem and showed the correct Open/Closed status.

### Versions

- **Plugin**: `1.0.0-rc1`

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

### Device Simulation Report

When Closed
```
[code]
	##### DEVICE DATA DUMP #####
	
	address : 
	batteryLevel : None
	buttonGroupCount : 0
	configured : True
	description : Status On when Garage Door Open, Status Off when Garage Door Closed
	deviceTypeId : pseudoRelay
	displayStateId : onOffState
	displayStateImageSel : PowerOff
	displayStateValRaw : False
	displayStateValUi : off
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 1302595955
	globalProps : MetaProps : (dict)
	     com.perceptiveautomation.indigoplugin.devicecollection : (dict)
	          doToggle : false (bool)
	          executionType : actionGroup (string)
	          offActionGroup : 544743683 (string)
	          onActionGroup : 544743683 (string)
	          statusRequestActionGroup : 544743683 (string)
	          statusVariable : 1224743440 (string)
	          supportsStatusRequest : true (bool)
	          toggleActionGroup :  (string)
	id : 1447377519
	lastChanged : 2018-04-20 11:26:41
	lastSuccessfulComm : 2018-04-20 11:26:41
	ledStates : []
	model : Virtual On/Off Device
	name : Garage Door Status
	onState : False
	ownerProps : com.perceptiveautomation.indigoplugin.devicecollection : (dict)
	     doToggle : false (bool)
	     executionType : actionGroup (string)
	     offActionGroup : 544743683 (string)
	     onActionGroup : 544743683 (string)
	     statusRequestActionGroup : 544743683 (string)
	     statusVariable : 1224743440 (string)
	     supportsStatusRequest : true (bool)
	     toggleActionGroup :  (string)
	pluginId : com.perceptiveautomation.indigoplugin.devicecollection
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Plugin
	remoteDisplay : True
	states : States : (dict)
	     onOffState : off (on/off bool)
	subModel : 
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsStatusRequest : True
	version : None
	
	##### DEVICE SIMULATION DATA #####
	
	Service : 
		alias : Garage Door Status
		model : 
		subModel : 
		indigoType : indigo.RelayDevice
		pluginType : indigo.RelayDevice.com.perceptiveautomation.indigoplugin.devicecollection.pseudoRelay
		type : GarageDoorOpener
		desc : Garage Door Opener
		objId : 1447377519
		serverId : 1790594891
		invertOnState : False
		convertFahrenheit : False
		required : (List)
			ObstructionDetected : False
			TargetDoorState : 0
			CurrentDoorState : 0
		optional : (List)
			LockTargetState
			Name
			LockCurrentState
		native : True
		requiresPlugin : (List)
		actions : (List)
			Action : (HomeKitAction)
				Characteristic : TargetDoorState
				When : equal
				Value : 0 (int)
				Value2 : 0 (int)
				Command : device.turnOff
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : TargetDoorState
				When : equal
				Value : 1 (int)
				Value2 : 0 (int)
				Command : device.turnOn
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : CurrentDoorState
				When : equal
				Value : 0 (int)
				Value2 : 0 (int)
				Command : device.turnOff
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : CurrentDoorState
				When : between
				Value : 1 (int)
				Value2 : 4 (int)
				Command : device.turnOn
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
		loadOptional : False
		characterDict : (Dict)
			ObstructionDetected : False
			TargetDoorState : 0
			CurrentDoorState : 0
	

	[/code]
```
When Open
```
[code]
	##### DEVICE DATA DUMP #####
	
	address : 
	batteryLevel : None
	buttonGroupCount : 0
	configured : True
	description : Status On when Garage Door Open, Status Off when Garage Door Closed
	deviceTypeId : pseudoRelay
	displayStateId : onOffState
	displayStateImageSel : PowerOn
	displayStateValRaw : True
	displayStateValUi : on
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 1302595955
	globalProps : MetaProps : (dict)
	     com.perceptiveautomation.indigoplugin.devicecollection : (dict)
	          doToggle : false (bool)
	          executionType : actionGroup (string)
	          offActionGroup : 544743683 (string)
	          onActionGroup : 544743683 (string)
	          statusRequestActionGroup : 544743683 (string)
	          statusVariable : 1224743440 (string)
	          supportsStatusRequest : true (bool)
	          toggleActionGroup :  (string)
	id : 1447377519
	lastChanged : 2018-04-20 15:30:52
	lastSuccessfulComm : 2018-04-20 15:30:52
	ledStates : []
	model : Virtual On/Off Device
	name : Garage Door Status
	onState : True
	ownerProps : com.perceptiveautomation.indigoplugin.devicecollection : (dict)
	     doToggle : false (bool)
	     executionType : actionGroup (string)
	     offActionGroup : 544743683 (string)
	     onActionGroup : 544743683 (string)
	     statusRequestActionGroup : 544743683 (string)
	     statusVariable : 1224743440 (string)
	     supportsStatusRequest : true (bool)
	     toggleActionGroup :  (string)
	pluginId : com.perceptiveautomation.indigoplugin.devicecollection
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Plugin
	remoteDisplay : True
	states : States : (dict)
	     onOffState : on (on/off bool)
	subModel : 
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsStatusRequest : True
	version : None
	
	##### DEVICE SIMULATION DATA #####
	
	Service : 
		alias : Garage Door Status
		model : 
		subModel : 
		indigoType : indigo.RelayDevice
		pluginType : indigo.RelayDevice.com.perceptiveautomation.indigoplugin.devicecollection.pseudoRelay
		type : GarageDoorOpener
		desc : Garage Door Opener
		objId : 1447377519
		serverId : 1790594891
		invertOnState : False
		convertFahrenheit : False
		required : (List)
			ObstructionDetected : False
			TargetDoorState : 1
			CurrentDoorState : 1
		optional : (List)
			LockTargetState
			Name
			LockCurrentState
		native : True
		requiresPlugin : (List)
		actions : (List)
			Action : (HomeKitAction)
				Characteristic : TargetDoorState
				When : equal
				Value : 0 (int)
				Value2 : 0 (int)
				Command : device.turnOff
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : TargetDoorState
				When : equal
				Value : 1 (int)
				Value2 : 0 (int)
				Command : device.turnOn
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : CurrentDoorState
				When : equal
				Value : 0 (int)
				Value2 : 0 (int)
				Command : device.turnOff
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : CurrentDoorState
				When : between
				Value : 1 (int)
				Value2 : 4 (int)
				Command : device.turnOn
				Arguments : [1447377519]
				monitors : {1447377519: 'attr_onState'}
		loadOptional : False
		characterDict : (Dict)
			ObstructionDetected : False
			TargetDoorState : 1
			CurrentDoorState : 1
	

	[/code]
```

**Comment by Colorado4Wheeler** [comment]
That's interesting considering absolutely nothing changed regarding devices or how they are referenced or how they are treated between versions.  When you created this ticket there should have been a whole large set of instructions on how you should report issues, did you delete all of that and decide not to post or did you post this ticket using a different method?  Those instructions included the information I would like to get when opening a ticket, such as a full simulation of any device that you are reporting as incorrect.  In your case I would want to see the simulation of the problematic device in both an open and closed state so I can see what is being sent to HomeKit.

**Comment by grwilde** [comment]
I will reopen the issue again providing the simulation report. I do know that there had to be some changes because the Home App icon for the garage door changed from a door to a garage door between versions. The problem I see is that the Garage Door reports open when closed and closed when open regardless of whether I set the Invert Open/Closed status or not.

**Comment by Colorado4Wheeler** [comment]
Don’t open a new issue, just add the simulation data to this one.

**Comment by Colorado4Wheeler** [comment]
According to what you just posted, HomeKit is being properly told that your door is open or closed:

	states : States : (dict)
	     onOffState : off (on/off bool)

		characterDict : (Dict)
			ObstructionDetected : False
			TargetDoorState : 0
			CurrentDoorState : 0

	states : States : (dict)
	     onOffState : on (on/off bool)

		characterDict : (Dict)
			ObstructionDetected : False
			TargetDoorState : 1
			CurrentDoorState : 1

Please restart your HomeKit Bridge server, then open and close your garage door and post the Homebridge Log (in the same place as the simulation command) so I can see what Homebridge is seeing or doing.

**Comment by Colorado4Wheeler** [comment]
By the way, you are using a virtual device for this, that's not really a supported garage door but you mentioned that the icon changed - the plugin cannot change your icon for you, you would have had to have changed the device type to go from a door to a garage door.  That being said, try configuring this as a contact sensor and see if that changes anything.  The invert may not work properly on your type of virtual device - something I will look into, but that may be why it appeared to work before: it was a contact sensor or something rather than a garage door.

**Comment by grwilde** [comment]
My virtual device was using an Indigo trigger to sense an Insteon EZIO device to determine whether the Garage Door was open or closed. (The EZIO device could also control the Garage Door to open or close it). When the Garage Door was closed the virtual device was off and when the Garage Door was open the virtual device was on. This has worked very well for years, and when I added it to Homekit Bridge a while ago it also seemed to work with the Home App (at least up to the latest update when the Open/Closed states suddenly reversed). In any event I solved my problem very easily just by inverting the state of the Closed/Open trigger. The Home App now shows the proper Open/Closed status of the Garage Door even though my virtual device now shows ON when the door is closed and OFF when the door is open. The following are the logs you requested (this was before I made the above change). It looks like Homekit Bridge was changing the status from 0 to 1 when I opened the Garage Door an from 1 to 0 when I closed it. That would seem to be correct and I have no idea why the Home App interpreted it differently. In any event it now shows the correct state, and reacts almost instantly when being opened or closed.

[2018-4-20 19:32:32] [HomeKit Bridge Server] POST update request for device ID 5fc05d85d429f9301d8bb9545a937800a07d52a7ef54f946361318fb1054097f
[2018-4-20 19:32:32] [HomeKit Bridge Server] Garage Door Status: updateCharacteristicValue(TargetDoorState): 0 -> 1
[2018-4-20 19:32:32] [HomeKit Bridge Server] Garage Door Status: updateCharacteristicValue(CurrentDoorState): 0 -> 1
[2018-4-20 19:32:41] [HomeKit Bridge Server] POST update request for device ID 5fc05d85d429f9301d8bb9545a937800a07d52a7ef54f946361318fb1054097f
[2018-4-20 19:32:41] [HomeKit Bridge Server] Garage Door Status: updateCharacteristicValue(TargetDoorState): 1 -> 0
[2018-4-20 19:32:41] [HomeKit Bridge Server] Garage Door Status: updateCharacteristicValue(CurrentDoorState): 1 -> 0

**Comment by Colorado4Wheeler** [comment]
Do you use the EZIO garage door kit?  That is what I use and the plugin supports that natively, without having to use the virtual device, just FYI.

**Comment by Colorado4Wheeler** [comment]
Even if you didn't get the kit, I think your device will work natively.

**Comment by grwilde** [comment]
I am using an Insteon EZIO2X4 I/O Controller that I purchased many years ago, long before the garage door kit existed. I am not sure if it is even sold anymore. A number of years ago I connected it to my Genie Garage Door opener, as well as my home security system and a water sensor. The garage door open/close sensor is a magnetic contact closure and the security system provides a voltage to the EZIO when set off. Basically I am using Indigo triggers to sense changes in these devices. The output of the controller sends a signal to the Genie to open or close the garage door. I am not sure if I could connect these devices natively, but the virtual devices using variables set by the triggers seem to work OK. The Home App indicates a change in the Open/Close status and sends a notification within a second or so, and is very responsive to changes. Perhaps there is a better way to do the same thing natively. Do you know if the plugin supports the Insteon EZIO2X4 I/O Controller?

**Comment by Colorado4Wheeler** [comment]
If it’s an IOLinc that supports binary input then I think what you have is the same as what I have, magnetic sensors and all.  Mine I have wired directly to my garage door opener so that I can just interface directly with it.

**Comment by grwilde** [comment]
I did check and the EZIO 2X4 module is still sold by Smarthome.  But I did not see how your plugin can selectively use the four separate inputs and two separate outputs of this module. In any event this is not a big deal since my solution appears to work fine. I love your Homekit Bridge plugin and how it opens up a lot of new capabilities to Insteon users!

**Comment by Colorado4Wheeler** [comment]
It doesn't, it only uses the first one.  I'm glad you got things worked out :).
