### ISSUE TITLE
Indigo not communicating to Homekit

### ISSUE THREAD

**Issue by whmoorejr** [Colorado4Wheeler/HomeKit-Bridge#106]
Changing device states (Insteon Lights & Fans, DCS Alarm, I/O Links) outside of Homekit (via indigo or at the physical switch) does not update the device status in Homekit.

### Steps to Reproduce (for bugs)
Any action to change a device state from any platform other than homekit fails to update the status in homekit.  

### Versions
V1.0.0

Machine running indigo was hung-up and needed to be restarted.  After restart, all is good.
(I didn't see a way to delete my "issue".)

**Comment by Colorado4Wheeler** [comment]
Seeing as you updated the forums to indicate that this was all the result of a problem on your server being hung up on other applications is this still a valid ticket?

**Comment by whmoorejr** [comment]
Not a valid ticket.  User error and I appreciate your tolerance of me.

**Comment by Colorado4Wheeler** [comment]
Yea, I closed the ticket - which is what you can do if it’s no longer valid since it is not possible to delete a ticket on Git.  Glad everything is working now!
