### ISSUE TITLE
Homekit updating but not indigo with Siri voice commands

### ISSUE THREAD

**Issue by nydave** [Colorado4Wheeler/HomeKit-Bridge#107]
### Expected Behavior
When i tell siri to turn a light on or off i expect it to do so.

### Current Behavior
If a light is on and i say hey siri turn light off it turns the light off and updates homekit.  If i tell it to turn same light on it says ok and updates homekit but the light doesnt turn on.  ststus does change in homekit but light doesnt turn on.

### Versions

- **Plugin**: 1.0.0-rc1 

### Configuration

```json

```

### Homebridge Log / Command Output

```
Apr 26, 2018 at 12:51:30 PM
   Virtual Devices                 sent "David's Office Lights" off
   Sent INSTEON                    "David's Office Lights (Slave)" off
   Sent INSTEON                    "David's Office Lights (Switch)" off

Thu, 26 Apr 2018 16:51:20 GMT EventedHTTPServer [::ffff:127.0.0.1] New connection from client
Thu, 26 Apr 2018 16:51:20 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 60311
Thu, 26 Apr 2018 16:51:20 GMT EventedHTTPServer [::ffff:127.0.0.1] Client connection closed
Thu, 26 Apr 2018 16:51:20 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP connection was closed
Thu, 26 Apr 2018 16:51:20 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server was closed
Thu, 26 Apr 2018 16:51:23 GMT EventedHTTPServer [::ffff:192.168.128.165] HTTP request: /characteristics
Thu, 26 Apr 2018 16:51:23 GMT HAPServer [CC:22:3D:E3:CE:10] HAP Request: PUT /characteristics
Thu, 26 Apr 2018 16:51:23 GMT Accessory [Archetti Home] Processing characteristic set: [{"aid":3,"iid":10,"value":true}]
Thu, 26 Apr 2018 16:51:23 GMT Accessory [Archetti Home] Setting Characteristic "On" to value true
Thu, 26 Apr 2018 16:51:23 GMT EventedHTTPServer [::ffff:192.168.128.165] HTTP Response is finished
Thu, 26 Apr 2018 16:51:30 GMT EventedHTTPServer [::ffff:192.168.128.165] HTTP request: /characteristics
Thu, 26 Apr 2018 16:51:30 GMT HAPServer [CC:22:3D:E3:CE:10] HAP Request: PUT /characteristics
Thu, 26 Apr 2018 16:51:30 GMT Accessory [Archetti Home] Processing characteristic set: [{"aid":3,"iid":10,"value":false}]
Thu, 26 Apr 2018 16:51:30 GMT Accessory [Archetti Home] Setting Characteristic "On" to value false
[2018-4-26 12:51:30] [HomeKit Bridge Server] David's Office Lights: set(On) true -> false
[2018-4-26 12:51:30] [HomeKit Bridge Server] HomeKit Bridge request: http://127.0.0.1:8558/HomeKit?objId=82225016&serverId=1381156041&jkey=d124fc3b83e5ecd390b11a52d9d78e47a8b5681d6d2d94e2b365a4b094822173&cmd=setCharacteristic&On=false
[2018-4-26 12:51:30] [HomeKit Bridge Server] David's Office Lights: updateCharacteristicValue(On): false -> true
Thu, 26 Apr 2018 16:51:30 GMT EventedHTTPServer [::ffff:192.168.128.165] HTTP Response is finished
Thu, 26 Apr 2018 16:51:39 GMT EventedHTTPServer [::ffff:192.168.128.165] HTTP request: /characteristics
Thu, 26 Apr 2018 16:51:39 GMT HAPServer [CC:22:3D:E3:CE:10] HAP Request: PUT /characteristics
Thu, 26 Apr 2018 16:51:39 GMT Accessory [Archetti Home] Processing characteristic set: [{"aid":3,"iid":10,"value":true}]
Thu, 26 Apr 2018 16:51:39 GMT Accessory [Archetti Home] Setting Characteristic "On" to value true
Thu, 26 Apr 2018 16:51:39 GMT EventedHTTPServer [::ffff:192.168.128.165] HTTP Response is finished
Thu, 26 Apr 2018 16:51:50 GMT EventedHTTPServer [::ffff:127.0.0.1] New connection from client
Thu, 26 Apr 2018 16:51:50 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 60316
Thu, 26 Apr 2018 16:51:50 GMT EventedHTTPServer [::ffff:127.0.0.1] Client connection closed
Thu, 26 Apr 2018 16:51:50 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP connection was closed
Thu, 26 Apr 2018 16:51:50 GMT EventedHTTPServer [::ffff:127.0.0.1] HTTP server was closed

```

##### DEVICE DATA DUMP #####
	
	address : 
	batteryLevel : None
	buttonGroupCount : 0
	configured : True
	description : 
	deviceTypeId : relayGroup
	displayStateId : onOffState
	displayStateImageSel : PowerOff
	displayStateValRaw : False
	displayStateValUi : off
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 1207692786
	globalProps : MetaProps : (dict)
	     com.perceptiveautomation.indigoplugin.devicecollection : (dict)
	          deviceList : (list)
	               Item : 1334550550 (string)
	               Item : 564729002 (string)
	          deviceListDict : {"relays": {}, "dimmers": {"564729002": 100, "1334550550": 100}} (string)
	          dimmerOnType : greaterThanOrEqual (string)
	          onOffType : allOn (string)
	          relayOnType : savedValue (string)
	          updateAllDevices : false (bool)
	id : 82225016
	lastChanged : 2018-04-26 12:51:31
	lastSuccessfulComm : 2018-04-26 12:51:31
	ledStates : []
	model : Device Group
	name : David's Office Lights
	onState : False
	ownerProps : com.perceptiveautomation.indigoplugin.devicecollection : (dict)
	     deviceList : (list)
	          Item : 1334550550 (string)
	          Item : 564729002 (string)
	     deviceListDict : {"relays": {}, "dimmers": {"564729002": 100, "1334550550": 100}} (string)
	     dimmerOnType : greaterThanOrEqual (string)
	     onOffType : allOn (string)
	     relayOnType : savedValue (string)
	     updateAllDevices : false (bool)
	pluginId : com.perceptiveautomation.indigoplugin.devicecollection
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Plugin
	remoteDisplay : True
	states : States : (dict)
	     onOffState : off (on/off bool)
	subModel : 
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsStatusRequest : True
	version : None
	
	##### DEVICE SIMULATION DATA #####
	
	Service : 
		alias : David's Office Lights
		model : 
		subModel : 
		indigoType : indigo.RelayDevice
		pluginType : indigo.RelayDevice.com.perceptiveautomation.indigoplugin.devicecollection.relayGroup
		type : Switch
		desc : Switch
		objId : 82225016
		serverId : 1381156041
		invertOnState : False
		convertFahrenheit : False
		required : (List)
			On : False
		optional : (List)
		native : True
		requiresPlugin : (List)
		actions : (List)
			Action : (HomeKitAction)
				Characteristic : On
				When : equal
				Value : False (bool)
				Value2 : 0 (bool)
				Command : device.turnOff
				Arguments : [82225016]
				monitors : {82225016: 'attr_onState'}
			Action : (HomeKitAction)
				Characteristic : On
				When : equal
				Value : True (bool)
				Value2 : 0 (bool)
				Command : device.turnOn
				Arguments : [82225016]
				monitors : {82225016: 'attr_onState'}
		loadOptional : False
		characterDict : (Dict)
			On : False
	

```

**Comment by Colorado4Wheeler** [comment]
Can you do another simulation output for when it is on?  That’s a device group, not a standard relay device and that may be the reason why it’s not working properly.

**Comment by Colorado4Wheeler** [comment]
Your HomeKit is acting far different than most people, switches just work and they always have.  I'll try with a virtual group like what you have here and see what happens.  But, no, there's no timeout - in fact it is quite instant.  Have you tried restarting your Indigo computer or anything like that?

**Comment by nydave** [comment]
well another reboot and update of all servers and devices appears to have resolved the issue.  Ill continue to test and let you know what i find.  thanks for the super fast reply.  You need some kind of go fund me page for all your effort.  thanks again

**Comment by Colorado4Wheeler** [comment]
I suspect your system may have been bogged down by another process.  If you ever ran Homebridge in any other form on there that may have also been jamming up the works.

In any case, I'm very happy you can make use of it now!  I can't think of any of us who probably need it more than your son, for us it's a toy but for him that's a pretty nice ability to have I imagine.

As for funding, I can give you wire instructions for a couple of million of you want 🤓.

**Comment by nydave** [comment]
thanks he appreciates it.  i just set it up for him.  his response..."sweet"
And when i win lotto sure ill get right on that transfer.

**Comment by Colorado4Wheeler** [comment]
Nah, that’s payment enough.  There’s far too little real rewards for doing this kind of plugin work but giving your son the ability to do something he never could before is a pretty nice payment for me.  But, if you win the lotto I’m holding you to that 2 mil!
