### ISSUE TITLE
Can't Start A HomeKit Server

### ISSUE THREAD

**Issue by alfacruxis** [Colorado4Wheeler/HomeKit-Bridge#108]
Changed HomeBridge Buddy for the HomeKit plugin and after creating a server and trying to start it I get the following message in the log window:

-------------------------
HomeKit Bridge Error            HomeKit server 'HomeKit Server' could not be started, please check the service logs for more information,
now issuing a forced shutdown of the service to be safe.

If you continue to have problems starting this server use the Advanced Plugin Actions menu option to rebuild the Homebridge folder.
Instructions at https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#rebuild-homebridge-folder
   HomeKit Bridge                  Attempting to stop 'HomeKit Server'
   HomeKit Bridge                  HomeKit server 'HomeKit Server' has been stopped
   HomeKit Bridge Error            send "HomeKit Server" on failed_
------------------------

I tried to rebuild the plugin folder from the advanced menu, but without any success.
Suggestions?
Thanks for your time.

**Comment by Colorado4Wheeler** [comment]
Please reload your plugin from the menu, sometimes if you have HBB it may need that.  Also, did you read the HBB migration wiki that is posted?

**Comment by alfacruxis** [comment]
I have read it. 
Anyway since I only had a test server with a couple of devices, I just deleted it all along.
I uninstalled and reinstalled all over and now is working well.
Thanks for your time and your help!

**Comment by Colorado4Wheeler** [comment]
Excellent!  👍🏻
