### ISSUE TITLE
NEST Thermostat "blip" caused removal of thermostats from HomeKit

### ISSUE THREAD

**Issue by mlamoure** [Colorado4Wheeler/HomeKit-Bridge#109]
### Current Behavior

I was actively working with my Indigo setup when I recieved warnings about my two NEST thermostats being removed from HomeKit Bridge.  I looked at the devices and they were still present in Indigo, but I noticed that they had blanked out their values for most thermostat relavent devices like the current temp, set points, modes, etc.  There were no errors in the logs pertaining to the NEST plugin.

### Steps to Reproduce (for bugs)
Have not been able to reproduce yet.

### Versions

- **Plugin**: `1.0.0 rc 1`
NEST: 2.0.50

### Configuration
Let me know if you need this.

### Homebridge Log / Command Output

```
HomeKit Bridge Warning          Indigo device Downstairs Thermostat was removed and is linked to HomeKit, removing from any impacted servers
   HomeKit Bridge                  Caching all HomeKit Bridge devices...
   HomeKit Bridge Error            Exception in homekit.special_nestHvacMode line 1805: 'key id 1288559663 not found in database'
							 CODE: obj = indigo.devices[self.objId]

For object id 1288559663 alias 'Upstairs Thermostat'
   HomeKit Bridge Error            Exception in homekit.special_thermTemperatureSetPoint line 1921: 'key id 1288559663 not found in database'
							 CODE: obj = indigo.devices[self.objId]

For object id 1288559663 alias 'Upstairs Thermostat'
   HomeKit Bridge Error            Exception in homekit.detCharacteristicValues line 1003: 'key id 1288559663 not found in database'
							 CODE: obj = indigo.devices[self.objId]

For object id 1288559663 alias 'Upstairs Thermostat'
   HomeKit Bridge Error            Exception in homekit.detCharacteristicValues line 1000: 'key id 1288559663 not found in database'
							 CODE: if getter.replace("attr_", "") in dir(indigo.devices[self.objId]): hasvalue = True

For object id 1288559663 alias 'Upstairs Thermostat'
   HomeKit Bridge Warning          Indigo device Upstairs Thermostat was removed and is linked to HomeKit, removing from any impacted servers
   HomeKit Bridge                  Caching all HomeKit Bridge devices...
   HomeKit Bridge                  Caching all HomeKit Bridge devices...
   HomeKit Bridge                  Attempting to stop 'HomeKit Bridge'
   Sonos                           SoCo Reactor Ignition...
   HomeKit Bridge                  HomeKit server 'HomeKit Bridge' has been stopped
   HomeKit Bridge Warning          Device ID 1288559663 (Upstairs Thermostat) is linked to server 'HomeKit Bridge' but that device ID no longer exists in Indigo and will be removed from the configuration
   HomeKit Bridge                  Caching all HomeKit Bridge devices...
   HomeKit Bridge                  Attempting to start 'HomeKit Bridge'
   Grafana Home Dashboard          a value (-32768.0) for device Front Porch Luminance was not in the configured range (-10000.0, 10000.0) and will not be sent to InfluxDB
   HomeKit Bridge                  Server 'HomeKit Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge                  Caching all HomeKit Bridge devices...
   HomeKit Bridge                  Attempting to stop 'HomeKit Bridge'
   HomeKit Bridge                  HomeKit server 'HomeKit Bridge' has been stopped
   HomeKit Bridge                  Attempting to start 'HomeKit Bridge'
   HomeKit Bridge                  Server 'HomeKit Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   Z-Wave                          received "Foyer Motion Sensor" status update is off

May 11, 2018 at 11:39:20 AM
   Error                           device "Downstairs Thermostat" state key humidityInput1 not defined (ignoring update request)
   Error                           device "Downstairs Thermostat" state key humidityInputsAll not defined (ignoring update request)
   Error                           device "Downstairs Thermostat" state key humidityInput1 not defined (ignoring update request)

```

### Device Simulation Report
Let me know if you need this.

**Comment by mlamoure** [comment]
You are right about the device ID for the thermostats.  I just confirmed that they changed after this ordeal.  I did not update or actively do anything with the NEST plugin.  Yesterday I linked my NEST account with Haiku fans, but that was it.

The NEST plugin auto creates the devices from your NEST account.  There is ZERO useful information in the logs folder for the Nest plugin.  If I need to provide this bug over to Chameleon, I have very little to give him.  

Luckily I dont have any triggers or actions for those devices, otherwise, I'd have a fun time ahead making the cascading changes.  I only set home/away status via the Home Master, which didn't change.

So, this is not a bug with HomeKit Bridge it would seem?

**Comment by Colorado4Wheeler** [comment]
No, I don’t believe it is for a number of reasons - for one it doesn’t have the ability to delete another plugin’s device and re-create it nor would I ever have a reason to write that into the plugin.  I also run Nest and haven’t had anything like that happen to me yet, but when I upgraded it late last year it wiped out my Nest devices and recreated them and it did reach havoc on my system until I manually fixed the bunch of triggers and actions that referred to the Nest.

**Comment by mlamoure** [comment]
FYI - https://forums.indigodomo.com/viewtopic.php?f=170&t=20810&p=161582#p161582
