### ISSUE TITLE
How did you implenent the Doorbell type?

### ISSUE THREAD

**Issue by HVR88** [Colorado4Wheeler/HomeKit-Bridge#144]
@Colorado4Wheeler I've recently moved to Home Assistant as you did last year - in 2022 it's finally ready where I can easily do everything I need with it, and just about ready where I can deploy it to customers comfortably.

So, one very specific aspect of your Homekit Bridge I love is the ability to mark any device/entity as any Homekit device type, for example the Doorbell type. Specific to the Doorbell type, what are you reporting to Homekit to prevent the requirement of a video feed?

With your plugin I can mark any momentary binary sensor/switch as a doorbell and in Homekit this allows Homepods to react with their Doorbell chime when the switch is activated. In this plugin, defining "Doorbell" type produces a switch in Homekit labelled as "unsupported accessory" - but which works perfectly fine with HomePod's Chime features.

But in Home Assistant's Homekit integration there's no such ability and the only way to expose "Doorbell" to Homekit is to make a VIDEO DOORBELL which always produces a video feed in Homekit and doesn't show a separate switch as a chime (it's integrated into the video feed of the camera device).

 Are you open to trying to get a switch working in Home Assistant as a doorbell the way you've managed here?

**Comment by Colorado4Wheeler** [comment]
Have you reviewed the docs on the [HA HomeKit implementation](https://www.home-assistant.io/integrations/homekit/)?  You can use any sensor as a linked doorbell sensor to provide the same functionality.  The difference with HA is that you set up your functionality in HA and can translate it to HomeKit.  I don't know if I understand the full implementation you are looking for but it sounds like you just need a binary sensor in HA to indicate the doorbell and then use that sensor in your HomeKit config to define a doorbell.

And if you need a switch to do the trick, then you create a sensor template tied to the switch and get the same result.

If you want, hit me on on the HA forums with a PM and we can chat more about it.

**Comment by HVR88** [comment]
👍🏼 I'll ping you on the HA forum - I wasn't sure you were there with the same name, so this was the easiest way I could think of to get a hold of you. ;)

I hadn't looked yet at (also) configuring HA's Homekit integration via YAML, as I didn't want to spawn another instance of the integration. It's not possible in the UI to manually declare the type, the integration only does it automatically unfortunately.  I see that I can probably declare en entity via YAML and simply skip all the camera bits and use only a binary sensor as the linked_doorbell_sensor.

**Comment by HVR88** [comment]
I thought you were using the same userID on the HA community, but I can't find a match right now. What ID should I PM? My ID is the same as here on github.

**Comment by HVR88** [comment]
If anyone else comes in here because they've moved from Indigo to Home Assistant, as of today, it doesn't seem possible to make a non-camera doorbell in Homekit using Home Assistant like you can with the HomeKit-Bridge in Indigo.

There's no support for declaring type of a switch entity as 'doorbell' and the only doorbell-specific property supported by Home Assistant for its Homekit integration is 'linked_doorbell_sensor' which can only be applied to a camera entity and isn't exposed itself as a switch inside Homekit.
