### ISSUE TITLE
Indigo 2022.1.0 compatibility

### ISSUE THREAD

**Issue by paul-e-m** [Colorado4Wheeler/HomeKit-Bridge#145]
Indigo's plug-in store indicates that this plug-in may not be compatible with versions after Indigo 2022.1.0. All embedded and external Python scripts are now executed in Python 3.10.
See https://www.indigodomo.com/docs/2022.1/getting_started#python_script_changes_and_plugin_compatibility

**Comment by FlyingDiver** [comment]
This plugin is obsolete and no longer maintained.  There is a replacement plugin under active development. See https://forums.indigodomo.com/viewforum.php?f=366

**Comment by paul-e-m** [comment]
Thanks @FlyingDiver. I'll switch over to that HomeKitLink Plugin Beta Release.
