### ISSUE TITLE
Camera previews work but not fullscreen

### ISSUE THREAD

**Issue by ericwass** [Colorado4Wheeler/HomeKit-Bridge#146]
I'm using Cynical SecuritySpy to provide camera feeds to HomeKit. What I'm experiencing is that camera previews work well and update the frame every ten seconds, as do PIP windows, but if I try to expand the image and get a live fullscreen feed, the image dims, I get the "waiting" clock icon and then, finally, "No Response - This camera is not responding." Seems to happen across platforms more or less. I described what happens on iOS. But on Mac I don't get the dim image or the waiting clock icon, just a warning that the camera is not responding. Any thoughts about what could be causing it and what I might do to fix it?

Indigo 2022.1.0
HomeKit Bridge 1.0.2
Cynical SecuritySpy 3.0.1

**Comment by FlyingDiver** [comment]
This plugin is obsolete and no longer maintained.  You'd be better asking in the forums if someone has seen this.  But no one will be working on attempting to reproduce or fix this issue.

**Comment by FlyingDiver** [comment]
There is a replacement plugin under active development.  See https://forums.indigodomo.com/viewforum.php?f=366

**Comment by ericwass** [comment]
Oh wow. Didn't know that. Ok, thanks very much.
