### ISSUE TITLE
Need type and versByte to recognize

### ISSUE THREAD

**Issue by Colorado4Wheeler** [Colorado4Wheeler/HomeKit-Bridge#5]
Type and versByte being sent to HB-Indigo2 as requested in the code comments but it's not yet picking them up.  Side note, does versByte need to be numeric or in version format or is it freeform?

**Comment by webdeck** [comment]
Added to homebridge-indigo2

**Comment by Colorado4Wheeler** [comment]
Fantastic, I'll run that through and see how it works.  The current release already has full support for that so hopefully just a matter of updating the build and it should just simply work.
