### ISSUE TITLE
Unable to set the value of CarbonMonoxideLevel

### ISSUE THREAD

**Issue by IndigoVaillant** [Colorado4Wheeler/HomeKit-Bridge#55]
**On Plugin (0.16.3) Reload getting:**
HomeKit Bridge Warning          Unable to set the value of CarbonMonoxideLevel on Kelder Carbon Monoxide Alarm to None because that attribute requires float and it was given NoneType

       **Device info:**
	allowOnStateChange : True
	allowSensorValueChange : False
	batteryLevel : 100
	buttonGroupCount : 0
	configured : True
	description : Vision
	deviceTypeId : zwOnOffSensorType
	displayStateId : onOffState
	displayStateImageSel : SensorOff
	displayStateValRaw : False
	displayStateValUi : off
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 804351588
	globalProps : MetaProps : (dict)
		 com.perceptiveautomation.indigoplugin.zwave : (dict)
			  AllowOnStateChange : true (bool)
			  SupportsBatteryLevel : true (bool)
			  SupportsEnergyMeter : false (bool)
			  SupportsEnergyMeterCurPower : false (bool)
			  SupportsEnergyMeterReset : false (bool)
			  SupportsOnState : true (bool)
			  SupportsSensorValue : false (bool)
			  SupportsStatusRequest : false (bool)
			  TempUnits : 1 (integer)
			  address : 37 (integer)
			  indigoObjVersion : 6 (integer)
			  propsPushTickler : 2 (string)
			  tempAlwaysFalse : false (bool)
			  userPollAfterActivity : true (bool)
			  userPollInterval : 0 (integer)
			  userPollingEnabled : true (bool)
			  userWakeInterval : 1440 (integer)
			  version : 3.05 (string)
			  zwAppVersMajor : 3 (integer)
			  zwAppVersMinor : 5 (integer)
			  zwAssociationsMap : (dict)
				   g1 : (list)
						Item : 1 (integer)
			  zwAssociationsMapStr : 1:[1] (string)
			  zwClassCmdBase : 113 (integer)
			  zwClassCmdMap : (dict)
				   c113 : 1 (integer)
				   c114 : 1 (integer)
				   c128 : 1 (integer)
				   c132 : 2 (integer)
				   c133 : 1 (integer)
				   c134 : 1 (integer)
				   c32 : 1 (integer)
			  zwClassCmdMapStr : 20v1 80v1 72v1 84v2 85v1 86v1 71v1 (string)
			  zwClassIds : (list)
				   Item : 4 (integer)
				   Item : 161 (integer)
				   Item : 7 (integer)
			  zwClassInstanceCountMap : (dict)
			  zwClassInstanceCountMapStr : - none - (string)
			  zwClassName : Smoke Sensor (routing) (string)
			  zwConfigVals : (dict)
			  zwConfigValsStr : - none - (string)
			  zwDevSubIndex : 0 (integer)
			  zwEndpointClassMap : (dict)
			  zwEndpointClassMapStr : - none - (string)
			  zwEndpointDevTypeMap : (dict)
			  zwEndpointDevTypeMapStr : - none - (string)
			  zwFeatureListStr : routing, battery, beaming, waking (string)
			  zwLibType : 6 (integer)
			  zwManufactureId : 265 (integer)
			  zwManufactureName : Vision / Yale (string)
			  zwMeterSubTypeFlags : 0 (integer)
			  zwMeterSupportsReset : false (bool)
			  zwMeterType : 0 (integer)
			  zwModelDefnVers : 2 (integer)
			  zwModelId : 537857795 (integer)
			  zwModelName : Carbon Monoxide Alarm (ZS6301) (string)
			  zwNodeNeighbors : (list)
				   Item : 1 (integer)
				   Item : 2 (integer)
				   Item : 6 (integer)
				   Item : 9 (integer)
				   Item : 10 (integer)
				   Item : 11 (integer)
				   Item : 14 (integer)
				   Item : 15 (integer)
				   Item : 16 (integer)
				   Item : 20 (integer)
				   Item : 21 (integer)
				   Item : 22 (integer)
				   Item : 55 (integer)
				   Item : 58 (integer)
				   Item : 59 (integer)
				   Item : 60 (integer)
				   Item : 61 (integer)
				   Item : 66 (integer)
				   Item : 68 (integer)
			  zwNodeNeighborsStr : 1, 2, 6, 9, 10, 11, 14, 15, 16, 20, 21, 22, 55, 58, 59, 60, 61, 66, 68 (string)
			  zwProtoVersMajor : 3 (integer)
			  zwProtoVersMinor : 52 (integer)
			  zwShowMainUI : true (bool)
			  zwShowPollingUI : false (bool)
			  zwShowWakeIntervalUI : true (bool)
			  zwWakeInterval : 1440 (integer)
	id : 711988081
	lastChanged : 2018-03-11 02:54:50
	lastSuccessfulComm : 2018-03-11 02:54:50
	model : Carbon Monoxide Alarm (ZS6301)
	name : Kelder Carbon Monoxide Alarm
	onState : False
	ownerProps : com.perceptiveautomation.indigoplugin.zwave : (dict)
		 AllowOnStateChange : true (bool)
		 SupportsBatteryLevel : true (bool)
		 SupportsEnergyMeter : false (bool)
		 SupportsEnergyMeterCurPower : false (bool)
		 SupportsEnergyMeterReset : false (bool)
		 SupportsOnState : true (bool)
		 SupportsSensorValue : false (bool)
		 SupportsStatusRequest : false (bool)
		 TempUnits : 1 (integer)
		 address : 37 (integer)
		 indigoObjVersion : 6 (integer)
		 propsPushTickler : 2 (string)
		 tempAlwaysFalse : false (bool)
		 userPollAfterActivity : true (bool)
		 userPollInterval : 0 (integer)
		 userPollingEnabled : true (bool)
		 userWakeInterval : 1440 (integer)
		 version : 3.05 (string)
		 zwAppVersMajor : 3 (integer)
		 zwAppVersMinor : 5 (integer)
		 zwAssociationsMap : (dict)
			  g1 : (list)
				   Item : 1 (integer)
		 zwAssociationsMapStr : 1:[1] (string)
		 zwClassCmdBase : 113 (integer)
		 zwClassCmdMap : (dict)
			  c113 : 1 (integer)
			  c114 : 1 (integer)
			  c128 : 1 (integer)
			  c132 : 2 (integer)
			  c133 : 1 (integer)
			  c134 : 1 (integer)
			  c32 : 1 (integer)
		 zwClassCmdMapStr : 20v1 80v1 72v1 84v2 85v1 86v1 71v1 (string)
		 zwClassIds : (list)
			  Item : 4 (integer)
			  Item : 161 (integer)
			  Item : 7 (integer)
		 zwClassInstanceCountMap : (dict)
		 zwClassInstanceCountMapStr : - none - (string)
		 zwClassName : Smoke Sensor (routing) (string)
		 zwConfigVals : (dict)
		 zwConfigValsStr : - none - (string)
		 zwDevSubIndex : 0 (integer)
		 zwEndpointClassMap : (dict)
		 zwEndpointClassMapStr : - none - (string)
		 zwEndpointDevTypeMap : (dict)
		 zwEndpointDevTypeMapStr : - none - (string)
		 zwFeatureListStr : routing, battery, beaming, waking (string)
		 zwLibType : 6 (integer)
		 zwManufactureId : 265 (integer)
		 zwManufactureName : Vision / Yale (string)
		 zwMeterSubTypeFlags : 0 (integer)
		 zwMeterSupportsReset : false (bool)
		 zwMeterType : 0 (integer)
		 zwModelDefnVers : 2 (integer)
		 zwModelId : 537857795 (integer)
		 zwModelName : Carbon Monoxide Alarm (ZS6301) (string)
		 zwNodeNeighbors : (list)
			  Item : 1 (integer)
			  Item : 2 (integer)
			  Item : 6 (integer)
			  Item : 9 (integer)
			  Item : 10 (integer)
			  Item : 11 (integer)
			  Item : 14 (integer)
			  Item : 15 (integer)
			  Item : 16 (integer)
			  Item : 20 (integer)
			  Item : 21 (integer)
			  Item : 22 (integer)
			  Item : 55 (integer)
			  Item : 58 (integer)
			  Item : 59 (integer)
			  Item : 60 (integer)
			  Item : 61 (integer)
			  Item : 66 (integer)
			  Item : 68 (integer)
		 zwNodeNeighborsStr : 1, 2, 6, 9, 10, 11, 14, 15, 16, 20, 21, 22, 55, 58, 59, 60, 61, 66, 68 (string)
		 zwProtoVersMajor : 3 (integer)
		 zwProtoVersMinor : 52 (integer)
		 zwShowMainUI : true (bool)
		 zwShowPollingUI : false (bool)
		 zwShowWakeIntervalUI : true (bool)
		 zwWakeInterval : 1440 (integer)
	pluginId : com.perceptiveautomation.indigoplugin.zwave
	pluginProps : emptyDict : (dict)
	protocol : ZWave
	remoteDisplay : False
	sensorValue : None
	states : States : (dict)
		 batteryLevel : 100 (integer)
		 batteryLevel.ui : 100% (string)
		 onOffState : off (on/off bool)
	subModel : Carbon Monoxide Alarm
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsOnState : True
	supportsSensorValue : False
	supportsStatusRequest : False
	version : 3.05

**[MODERATOR NOTE: REFORMATTED DEVICE INFO TO MAKE IT MORE READABLE]**

**Comment by Colorado4Wheeler** [comment]
Can you please perform the [Simulate for Server Item](https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#simulate-homekit-for-server-item) and output that for me?

**Comment by IndigoVaillant** [comment]
Output:

[Dump.txt](https://github.com/Colorado4Wheeler/HomeKit-Bridge/files/1810484/Dump.txt)

**Comment by Colorado4Wheeler** [comment]
Thanks, I'll see if I can track down why it continues to report that.

**Comment by Colorado4Wheeler** [comment]
Ok, no joke this time, it's fixed in the next release :).  I was able to reproduce the problem and saw that my previous fix had a typo and my recreation of your device and this error are no longer reporting an issue and will properly report 0ppm in the Home app instead of nothing.
