### ISSUE TITLE
Use raspberry pi beacons for Occupancy Sensor

### ISSUE THREAD

**Issue by itopota** [Colorado4Wheeler/HomeKit-Bridge#57]
HomeKit Bridge Threaddebug      Advanced plugin menu performing 'simhomekit' on device 1563449205
	   HomeKit Bridge                  Simulating HomeKit values for ito chiavi
	   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
	   HomeKit Bridge                  address : DA:90:4F:C3:C3:9L
	batteryLevel : None
	buttonGroupCount : 0
	configured : True
	description : beacon_DA:90:4F:C3:C3:9L
	deviceTypeId : beacon
	displayStateId : displayStatus
	displayStateImageSel : SensorOn
	displayStateValRaw : up         03-12 17:11:23
	displayStateValUi : up         03-12 17:11:23
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 237526583
	globalProps : MetaProps : (dict)
		 com.karlwachs.piBeacon : (dict)
			  IgnoreBeaconIfSignalLessThan : -999 (string)
			  MSG : OK (string)
			  SupportsBatteryLevel : false (bool)
			  UUID : x-x-x (string)
			  address : DA:90:4F:C3:C3:9L (string)
			  beaconTxPower : 999 (integer)
			  created : 0 (integer)
			  expirationTime : 70 (integer)
			  fastDown : 25 (string)
			  fastDownMinSignal : -999 (integer)
			  ignore : 0 (string)
			  isBeaconDevice : true (bool)
			  memberOfFamily : true (bool)
			  memberOfGuests : false (bool)
			  memberOfOther1 : false (bool)
			  memberOfOther2 : false (bool)
			  minSignalCutoff : -999 (integer)
			  msg :  (string)
			  newMACNumber : DA:90:4F:C3:C3:9L (string)
			  note : beacon (string)
			  showBeaconNickName :  (string)
			  showBeaconOnMap : 0 (string)
			  showBeaconSymbolAlpha : 0.5 (string)
			  showBeaconSymbolColor :  (string)
			  showBeaconSymbolType : , (string)
			  showBeaconSymboluseErrorSize : 1 (string)
			  showBeaconTextColor :  (string)
			  signalDelta : 999 (integer)
			  typeOfBeacon : other (string)
			  updateSignalValuesSeconds : 0 (integer)
	id : 174562694
	lastChanged : 2018-03-12 19:17:03
	lastSuccessfulComm : 2018-03-12 19:17:03
	model : beacon
	name : ito chiavi
	ownerProps : com.karlwachs.piBeacon : (dict)
		 IgnoreBeaconIfSignalLessThan : -999 (string)
		 MSG : OK (string)
		 SupportsBatteryLevel : false (bool)
		 UUID : x-x-x (string)
		 address : DA:90:4F:C3:C3:9L (string)
		 beaconTxPower : 999 (integer)
		 created : 0 (integer)
		 expirationTime : 70 (integer)
		 fastDown : 25 (string)
		 fastDownMinSignal : -999 (integer)
		 ignore : 0 (string)
		 isBeaconDevice : true (bool)
		 memberOfFamily : true (bool)
		 memberOfGuests : false (bool)
		 memberOfOther1 : false (bool)
		 memberOfOther2 : false (bool)
		 minSignalCutoff : -999 (integer)
		 msg :  (string)
		 newMACNumber : DA:90:4F:C3:C3:9L (string)
		 note : beacon (string)
		 showBeaconNickName :  (string)
		 showBeaconOnMap : 0 (string)
		 showBeaconSymbolAlpha : 0.5 (string)
		 showBeaconSymbolColor :  (string)
		 showBeaconSymbolType : , (string)
		 showBeaconSymboluseErrorSize : 1 (string)
		 showBeaconTextColor :  (string)
		 signalDelta : 999 (integer)
		 typeOfBeacon : other (string)
		 updateSignalValuesSeconds : 0 (integer)
	pluginId : com.karlwachs.piBeacon
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Plugin
	remoteDisplay : True
	states : States : (dict)
		 Pi_0_Distance : 9999900.0 (real)
		 Pi_0_Signal : -62 (integer)
		 Pi_0_Time : 2018-03-12 19:16:59 (string)
		 Pi_1_Distance : 9999900.0 (real)
		 Pi_1_Signal : -67 (integer)
		 Pi_1_Time : 2018-03-12 19:16:58 (string)
		 Pi_2_Distance : 99999 (real)
		 Pi_2_Signal : -999 (integer)
		 Pi_2_Time :  (string)
		 Pi_3_Distance : 99999 (real)
		 Pi_3_Signal : -999 (integer)
		 Pi_3_Time :  (string)
		 Pi_4_Distance : 99999 (real)
		 Pi_4_Signal : -999 (integer)
		 Pi_4_Time :  (string)
		 Pi_5_Distance : 99999 (real)
		 Pi_5_Signal : -999 (integer)
		 Pi_5_Time :  (string)
		 Pi_6_Distance : 99999 (real)
		 Pi_6_Signal : -999 (integer)
		 Pi_6_Time :  (string)
		 Pi_7_Distance : 99999 (real)
		 Pi_7_Signal : -999 (integer)
		 Pi_7_Time :  (string)
		 Pi_8_Distance : 99999 (real)
		 Pi_8_Signal : -999 (integer)
		 Pi_8_Time :  (string)
		 Pi_9_Distance : 99999 (real)
		 Pi_9_Signal : -999 (integer)
		 Pi_9_Time :  (string)
		 PosX : 0 (integer)
		 PosY : 0 (integer)
		 PosZ : 0 (integer)
		 TxPowerReceived : 84 (real)
		 TxPowerSet : 999 (integer)
		 UUID : efd08370a247c89837e7b5634df524c3-20380-50123 (string)
		 closestRPI : 0 (integer)
		 closestRPIText : Pi_0 (string)
		 created : 2017-10-11 19:58:31 (string)
		 displayStatus : up         03-12 17:11:23 (string)
		 groupMember : Family (string)
		 lastStatusChange : 2018-03-12 17:11:23 (string)
		 note : beacon-other (string)
		 pkLen : 31 (integer)
		 status : up (string)
	subModel : 
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsStatusRequest : False
	version : None
	   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
	   HomeKit Bridge Threaddebug      Adding OccupancyDetected attribute to ito chiavi
	   HomeKit Bridge Threaddebug      Adding StatusLowBattery attribute to ito chiavi
	   HomeKit Bridge Debug            ito chiavi started as a HomeKit Occupancy Sensor
	   HomeKit Bridge                  Service : 
		alias : ito chiavi
		model : 
		subModel : 
		indigoType : indigo.Device
		pluginType : indigo.Device.com.karlwachs.piBeacon.beacon
		type : OccupancySensor
		desc : Occupancy Sensor
		objId : 174562694
		serverId : 1563449205
		invertOnState : False
		convertFahrenheit : False
		required : (List)
			OccupancyDetected : False
		optional : (List)
			StatusActive
			StatusFault
			StatusTampered
			Name
			StatusLowBattery : 0
		native : True
		requiresPlugin : (List)
		actions : (List)
		loadOptional : False
		characterDict : (Dict)

	   HomeKit Bridge Threaddebug      Generating custom list 'plugin' (filter: index=hkType, callback=onAfter_btnAdvDeviceAction_GetAttachedJSONDevices, ref=hideWrappedItems, nocache=true), typeId of advancedPluginActions, targetId of 0 and arguments: {u'ref': u'hideWrappedItems', u'nocache': u'true', u'callback': u'onAfter_btnAdvDeviceAction_GetAttachedJSONDevices'}
	   HomeKit Bridge Threaddebug      Generating custom list 'plugin' (filter: index=hkType, callback=serverListHomeKitDeviceTypes, ref=hideWrappedItems, nocache=true), typeId of advancedPluginActions, targetId of 0 and arguments: {u'ref': u'hideWrappedItems', u'nocache': u'true', u'callback': u'serverListHomeKitDeviceTypes'}

**Comment by Colorado4Wheeler** [comment]
Added support in the next release.
