### ISSUE TITLE
Sonos issue

### ISSUE THREAD

**Issue by rgspb** [Colorado4Wheeler/HomeKit-Bridge#62]
This setup was working under Homebridge Buddy but not under HomeKit Bridge. Here’s my setup:

I created a Virtual Device called “The Ocean”. Turning the device ON runs an Action Group called “Start Ocean”. Turning the device OFF runs an Action Group called “Stop Ocean”. 

I was successful getting “The Ocean” to the Home app. It is setup as a switch in the Home app. When I tell Siri to “turn on the ocean” it does. The Indigo log shows the command was received and and Start Ocean was run. The song begins to play through the Sonos speakers. The error then shows in the log: Maximum time exceeded while setting the ‘On’ HomeKit characteristic for ‘The Ocean’ (HomeKit device ‘The Ocean’), aborting attempt. This can happen if you try to set a device to a state is is already in (I.e., turning off a device that is already off). When I tell Siri to “turn off the ocean” It does not. The Indigo log does not indicate receiving the off command.

**Comment by Colorado4Wheeler** [comment]
Use the advanced plugin options menu item, then the device actions and select the HomeKit simulator for the server and device you are referring to, make sure you copy from the log notice that simulator is being run all the way to the bottom.  This lets me see what's what.

**Comment by rgspb** [comment]
OK, I hope this is everything you need. I just copied everything that it spit out into the log.
Thanks for your help!

Mar 16, 2018, 8:21:11 PM
   HomeKit Bridge                  Simulating HomeKit values for The Ocean
   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
   HomeKit Bridge                  address : 
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : pseudoRelay
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 719663863
globalProps : MetaProps : (dict)
     com.perceptiveautomation.indigoplugin.devicecollection : (dict)
          doToggle : false (bool)
          executionType : actionGroup (string)
          offActionGroup : 132680711 (string)
          onActionGroup : 1406958003 (string)
          statusRequestActionGroup :  (string)
          statusVariable :  (string)
          supportsStatusRequest : false (bool)
          toggleActionGroup :  (string)
id : 1191835603
lastChanged : 2000-01-01 00:00:00
lastSuccessfulComm : 2000-01-01 00:00:00
ledStates : []
model : Virtual On/Off Device
name : The Ocean
onState : False
ownerProps : com.perceptiveautomation.indigoplugin.devicecollection : (dict)
     doToggle : false (bool)
     executionType : actionGroup (string)
     offActionGroup : 132680711 (string)
     onActionGroup : 1406958003 (string)
     statusRequestActionGroup :  (string)
     statusVariable :  (string)
     supportsStatusRequest : false (bool)
     toggleActionGroup :  (string)
pluginId : com.perceptiveautomation.indigoplugin.devicecollection
pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None
   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
   HomeKit Bridge                  Service : 
	alias : The Ocean
	model : 
	subModel : 
	indigoType : indigo.RelayDevice
	pluginType : indigo.RelayDevice.com.perceptiveautomation.indigoplugin.devicecollection.pseudoRelay
	type : Switch
	desc : Switch
	objId : 1191835603
	serverId : 1629026996
	invertOnState : False
	convertFahrenheit : False
	required : (List)
		On : False
	optional : (List)
	native : True
	requiresPlugin : (List)
	actions : (List)
		Action : (HomeKitAction)
			Characteristic : On
			When : equal
			Value : False (bool)
			Value2 : 0 (bool)
			Command : device.turnOff
			Arguments : [1191835603]
			monitors : {1191835603: 'attr_onState'}
		Action : (HomeKitAction)
			Characteristic : On
			When : equal
			Value : True (bool)
			Value2 : 0 (bool)
			Command : device.turnOn
			Arguments : [1191835603]
			monitors : {1191835603: 'attr_onState'}
	loadOptional : False
	characterDict : (Dict)
		On : False

**Comment by Colorado4Wheeler** [comment]
Ok, so the fix for this is that you need to do a couple of things.  The reason this beachballs is because the status of your switch doesn't change (I've tested this to verify) unless you specify a variable that holds the status.  So when you turn it on the virtual device says it's still off and that's because it doesn't pull status from anywhere.  If you change your action groups to update a variable, say "SonosPlaying_Color" for example, to True when on and False when off then your problem will be fixed.

Why is this different than HBB?  Because we actually do testing here to make sure that the device action is successful, so we wait for the command to be sent, the device state to update (which yours never does) and then report back to HomeKit that it's on or off.  Even if we didn't do the test and simply reported back to HomeKit the current status then it would be the same since the onState never changes from True to False or False to True.

Make sense?  Try that and it should work just fine.

**Comment by rgspb** [comment]
That did it! Thank you so much!
