### ISSUE TITLE
Exception in plugin error

### ISSUE THREAD

**Issue by Highsteads** [Colorado4Wheeler/HomeKit-Bridge#64]
If you have a Homebridge server that is created but with no device or action and issue

Advanced Plugin Actions > Show Homebridge Log >Execute

It errors with

17 Mar 2018, 10:11:57
   HomeKit Bridge Error            Exception in plugin.onAfter_btnAdvDeviceAction line 903: [Errno 2] No such file or directory: '/Library/Application Support/Perceptive Automation/Indigo 7/Preferences/Plugins/com.eps.indigoplugin.homekit-bridge/378445279/homebridge.log'
							 CODE: file = open(startpath + "/homebridge.log", 'r')

as the log is only generated after the first device/action is saved. Cosmetic but just trying to break things ( thats what betas are for :)  )

**Comment by Colorado4Wheeler** [comment]
Correct, if you never start the Homebridge server then it will bomb on that function.  It's purely cosmetic but I'll trap the error.  My first thought was "why would I worry about that" but if someone's Homebridge isn't starting up and they try that function it would really only verify that Homebridge isn't starting but I can make that clearer.
