### ISSUE TITLE
Homekit bridge wont start

### ISSUE THREAD

**Issue by mortenkols** [Colorado4Wheeler/HomeKit-Bridge#65]
After i added more devices to homekit bridge, the plugin wont start anymore. i have tried to delete the device i added, but the problem is stil there. i have also tried to rebuild the homebridge folder. 

17. mar. 2018, 19:29:56
   Reloading plugin "HomeKit Bridge 0.18.0"
   Stopping plugin "HomeKit Bridge 0.18.0" (pid 28796)
   Stopped plugin "HomeKit Bridge 0.18.0"
   Starting plugin "HomeKit Bridge 0.18.0" (pid 32374)
   Started plugin "HomeKit Bridge 0.18.0"

17. mar. 2018, 19:30:59
   HomeKit Bridge Error            HomeKit server 'Bod Kjeller - HomeKit Bridge' could not be started, please check the service logs for more information, now issuing a forced shutdown of the service to be safe.

link to the log: https://www.dropbox.com/s/6wn2kdbamddoa9x/plugin.log?dl=0

**Comment by Colorado4Wheeler** [comment]
Please output the Homebridge log from the Advanced Plugin Actions menu so we can see what, if anything, HB is complaining about - but capture the log after you reload the plugin so we can see it clean.

**Comment by mortenkols** [comment]
17. mar. 2018, 21:01:02
   Reloading plugin "HomeKit Bridge 0.18.0"
   Stopping plugin "HomeKit Bridge 0.18.0" (pid 32374)
   Stopped plugin "HomeKit Bridge 0.18.0"
   Starting plugin "HomeKit Bridge 0.18.0" (pid 36826)
   Started plugin "HomeKit Bridge 0.18.0"
   HomeKit Bridge                  Attempting to start 'Bod Kjeller - HomeKit Bridge'

17. mar. 2018, 21:02:06
   HomeKit Bridge Error            HomeKit server 'Bod Kjeller - HomeKit Bridge' could not be started, please check the service logs for more information, now issuing a forced shutdown of the service to be safe.
   HomeKit Bridge                  Attempting to stop 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been stopped
   HomeKit Bridge                  HomeKit Bridge is loaded and ready to use

17. mar. 2018, 21:02:42
   HomeKit Bridge Error            Exception in plugin.onAfter_btnAdvDeviceAction line 904: 'str' object has no attribute 'is_file'
							 CODE: if fullpath.is_file():

**Comment by Colorado4Wheeler** [comment]
AGGGGGGGHHHHHHHHHHH.  There are a number of profane words I want to use right now.

**Comment by mortenkols** [comment]
okei..... what do you mean? ;D

**Comment by Colorado4Wheeler** [comment]
Because of this:

> HomeKit Bridge Error Exception in plugin.onAfter_btnAdvDeviceAction line 904: 'str' object has no attribute 'is_file'
CODE: if fullpath.is_file():

Is brand new code that I neglected to test, otherwise it would have spit out the log.

**Comment by mortenkols** [comment]
okei :D how can i get it to run again?

**Comment by Colorado4Wheeler** [comment]
I have no idea what is preventing it from starting so until I see that log I can't tell you.  You could go to the prefs folder and into the sub-folder for your server ID and pull it manually.  Homebridge.log is what we need to see.

**Comment by mortenkols** [comment]
module.js:549
    throw err;
    ^

Error: Cannot find module '/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/EPS HomeKit Bridge.indigoPlugin/Contents/Server Plugin/bin/hb/node-v8.10.0-darwin-x64/lib/cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/EPS HomeKit Bridge.indigoPlugin/Contents/Server Plugin/bin/hb/node-v8.10.0-darwin-x64/bin/homebridge:17:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by mortenkols** [comment]
deleted the plugin and added it again solved the problem in indigo. the plugin is running. but when i open the home app on my iphone nothing is updating.

**Comment by Colorado4Wheeler** [comment]
So it was a corrupted download.  I’m doing some final tests now on that character, right now I’ve gotten past that error and can see the device in HomeKit with that character so hopefully this will be it.

**Comment by mortenkols** [comment]
closed? its not working!!

**Comment by mortenkols** [comment]
the plugin is running but nothing gets updated in homekit

**Comment by Colorado4Wheeler** [comment]
The issue you reported on THIS ticket is no longer applicable, correct?  It's starting up and you are now still dealing with issue #63 regarding the special character.  Or do you have yet a third problem that you know is unrelated to the special character issue?
