### ISSUE TITLE
Camera Support:  Add support for BlueIris Cameras/Plugin?

### ISSUE THREAD

**Issue by Ghawken** [Colorado4Wheeler/HomeKit-Bridge#66]
Hi 
Thanks for this plugin - upgraded and all going well - hard to keep up with your updates though!

Wondering whether might extent beginning of Camera support to BlueIris Plugin Cameras?

These are the Server Device (One) and Camera Device (States)

![](https://image.ibb.co/ke8qXx/BIDevice_States.png)
&
![](https://image.ibb.co/hgtPsx/BIServer_States.png)

If you need me to add any state let me know!  
The BI Server IP/Port and Username/Password are Plugin Config properties in BlueIris Plugin.

These are the links to streams using Ip/Port/username/password.
The cam-short-name is the BI Camera State - optionValue

```
/h264/{cam-short-name}/temp.h264 Pull a raw H.264 stream (MIME type video/H264).  This stream will play in a tool like VLC, and may be used in future versions of the ActiveX control. 
/h264/{cam-short-name}/temp.ts Pull an MPEG-2 transport stream (MIME type video/MP2T). 
/h264/{cam-short-name}/temp.m or .m3u8 Pull a virtual M3U8 file (MIME type application/vnd.apple.mpegurl).  This will play in QuickTime, iPad and the iPhone using the iPhone Live Streaming format
&

Images
/image/{cam-short-name}?w={widthpixelsofImage}

[Width of Camera is a State in BI Camera]

```

&

CameraState Motion - true if motion
```
Motion
This is True/False depending whether the camera currently has detected Motion. 
Can be used to trigger events if motion detected - or can use Event trigger.
```

Thanks!

**Comment by FlyingDiver** [comment]
See http://forums.indigodomo.com/viewtopic.php?f=201&t=20373 where C4W requested data (and showed what he needed).

**Comment by Colorado4Wheeler** [comment]
Brilliant information, I'll see what I can work up.  Can you send me a PM with your prefs file for Blue Iris?  You can change the user/pass, I just need to see how it all comes together.

**Comment by Ghawken** [comment]
Will do
Had missed that earlier post !

**Comment by Colorado4Wheeler** [comment]
Also, just so I have a working example, can you send me an example full URL, that you have put into your browser and works?  IP address and all.  I need H.264 streams and stills too if Blue Iris has them.

**Comment by Ghawken** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<Prefs type="dict">
	<Httpserverport type="integer">4556</Httpserverport>
	<ImageTimeOut type="string"></ImageTimeOut>
	<ImageTimeout type="integer">10</ImageTimeout>
	<ServerTimeout type="integer">5</ServerTimeout>
	<advanced type="bool">false</advanced>
	<configMenuPollInterval type="string">300</configMenuPollInterval>
	<configMenuServerTimeout type="string">15</configMenuServerTimeout>
	<configUpdaterForceUpdate type="bool">true</configUpdaterForceUpdate>
	<configUpdaterInterval type="integer">2</configUpdaterInterval>
	<debugextra type="bool">false</debugextra>
	<debugextra2 type="bool">false</debugextra2>
	<debugextra3 type="bool">false</debugextra3>
	<debuggif type="bool">false</debuggif>
	<debugimage type="bool">false</debugimage>
	<debugother type="bool">false</debugother>
	<debugserver type="bool">false</debugserver>
	<debugtriggers type="bool">false</debugtriggers>
	<directory type="string">/Users/Indigo/Documents/Indigo-BlueIris/</directory>
	<generateCameras type="string"></generateCameras>
	<infoLabel0 type="string"></infoLabel0>
	<loginOK type="string">true</loginOK>
	<loginServer type="string"></loginServer>
	<openStore type="bool">true</openStore>
	<sep224 type="string"></sep224>
	<sep233 type="string"></sep233>
	<sep235 type="string"></sep235>
	<sep23ab5 type="string"></sep23ab5>
	<sep2aa24 type="string"></sep2aa24>
	<sep2aa33 type="string"></sep2aa33>
	<sep4 type="string"></sep4>
	<sep424aa type="string"></sep424aa>
	<sep44aa type="string"></sep44aa>
	<sep6 type="string"></sep6>
	<sep7 type="string"></sep7>
	<sep9 type="string"></sep9>
	<sepnew44 type="string"></sepnew44>
	<serverip type="string">192.168.1.208</serverip>
	<serverpassword type="string">demopassword</serverpassword>
	<serverport type="string">801</serverport>
	<serverusername type="string">testuser</serverusername>
	<showDebugInfo type="bool">false</showDebugInfo>
	<showDebugLevel type="integer">10</showDebugLevel>
	<shwoAlertText type="string"></shwoAlertText>
	<space0 type="string"></space0>
	<space1 type="string"></space1>
	<space10 type="string"></space10>
	<space11 type="string"></space11>
	<space2 type="string"></space2>
	<spacea2 type="string"></spacea2>
	<updateFrequency type="string">24</updateFrequency>
	<updaterEmail type="string"></updaterEmail>
	<updaterEmailsEnabled type="bool">false</updaterEmailsEnabled>
</Prefs>

```

**Comment by Colorado4Wheeler** [comment]
You can just put them here if you want, you don't have to put them both places.  Thank you :).

**Comment by Ghawken** [comment]
Image:

`http://192.168.1.208:801/image/Gate?w=1920`

Camera Shortname/optionValue = 'Gate'
Server IP/Port from PluginPrefs
Username/Password can be sent in url

http://192.168.1.208:801/h264/Gate/temp.h264

Pulls a constantly downloading file temp.h264 - doesn't playback in Chrome.  Just testing in VLC now

**Comment by Colorado4Wheeler** [comment]
Can you attach the prefs file for this (you can edit out any real usernames/passwords) so I can add it to my system for testing?  I'm going to be doing this 100% blind since I don't have this but I don't think it'll take too many releases to dial it in.

**Comment by Colorado4Wheeler** [comment]
Never mind, it won't do me any good anyway.

**Comment by Ghawken** [comment]
Happy to add/change camera states/hidden or otherwise so can more easily access ServerIp/Port/Username/Password? 
?add to camera device

**Comment by Colorado4Wheeler** [comment]
I don't know what you mean...  But,  you can try the latest build, I have experimental support for Blue Iris in there and I'm curious if it works.

**Comment by Colorado4Wheeler** [comment]
Just released [Beta 19.6](https://github.com/Colorado4Wheeler/HomeKit-Bridge/releases/tag/0.19.6) that patched a build error.

**Comment by Ghawken** [comment]
Great - will try when can in probably a few hours (life getting in way) (will see if can remote in a upgrade/setup)

Was checking out commits and saw the changes there. Exciting!

Would add that BI Camera Device also has a FPS setting. - custom state.

```
biHeight = biDev.states["height"]
biName = biDev.states["optionValue"]
biFPS = 30
eg. could be: biFPS =  biDev.states["FPS"]
```

Thanks

Glenn

**Comment by Colorado4Wheeler** [comment]
I could have sworn I couldn’t find FPS in the states, I thought for sure it would be there.  I must have simply overlooked it, I’ll put that into the next update.

**Comment by Colorado4Wheeler** [comment]
Oh, I know why I did that, because every one of the sample device dumps I got has FPS = 0 so I just defaulted it until I could find out more info about that or if I wanted to do some kind of checking to see if the camera was disabled or something.

**Comment by Colorado4Wheeler** [comment]
Now that I look at them, not EVERY one... :P.  I'll but some sanity checks for that.

**Comment by Ghawken** [comment]
Hi
On 19.6  ( via dodgy VPN tunnelled connection, so slow and hard to copy and paste)
Camera Devices adds, but getting
Line 4377 list index out of range error.

(will try and copy and paste if can)

**Comment by Colorado4Wheeler** [comment]
Yea, this build isn’t working for that.  I’m going to replicate something on my dev server to try to work past this bit.

**Comment by Colorado4Wheeler** [comment]
Ok, let's see if the third time is a charm - [release 0.19.7](https://github.com/Colorado4Wheeler/HomeKit-Bridge/releases/tag/0.19.7) should finally fix that pref file problem.

**Comment by Ghawken** [comment]
Ok.  Adds without error and remains on rechecking/restarting.
Arghh! though can't test it as away from Home and even though have remote access (old devices) work.  This new camera hasn't shown as yet.

**Comment by Colorado4Wheeler** [comment]
[On the forums Clive said it worked](http://forums.indigodomo.com/viewtopic.php?p=157077#p157077), so fingers crossed when you get home :).

**Comment by Ghawken** [comment]
Well done!

![](http://bestanimations.com/Holidays/Fireworks/fireworks/ba-awesome-colorful-fireworks-animated-gif-image-s.gif)


Good old Clive he was always fast with feedback!

**Comment by Ghawken** [comment]
Not quite there yet...  Still fireworks for Clive!

On my system - can add Camera as new Accessory - adds and finds.

Yet get a Camera/Crossed Icon with No reponse
This in Homekit - debug log
```
   HomeKit Bridge Threaddebug      Adding SelectedRTPStreamConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Converting value type of str to charateristic type of unicode for SelectedRTPStreamConfiguration
   HomeKit Bridge Threaddebug      Adding SetupEndpoints attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Adding SupportedAudioStreamConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Adding StreamingStatus attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Adding SupportedVideoStreamConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Converting value type of str to charateristic type of unicode for SupportedVideoStreamConfiguration
   HomeKit Bridge Threaddebug      Adding SupportedRTPConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Converting value type of str to charateristic type of unicode for SupportedRTPConfiguration
   HomeKit Bridge Debug            BlueIris Camera GateLPR started as a HomeKit Camera RTP Stream Management (Experimental)
   HomeKit Bridge Debug            Indigo device BlueIris Camera GateLPR changed and is linked to HomeKit, checking if that change impacts HomeKit
   HomeKit Bridge Threaddebug      Adding SelectedRTPStreamConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Converting value type of str to charateristic type of unicode for SelectedRTPStreamConfiguration
   HomeKit Bridge Threaddebug      Adding SetupEndpoints attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Adding SupportedAudioStreamConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Adding StreamingStatus attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Adding SupportedVideoStreamConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Converting value type of str to charateristic type of unicode for SupportedVideoStreamConfiguration
   HomeKit Bridge Threaddebug      Adding SupportedRTPConfiguration attribute to BlueIris Camera GateLPR
   HomeKit Bridge Threaddebug      Converting value type of str to charateristic type of unicode for SupportedRTPConfiguration
   HomeKit Bridge Debug            BlueIris Camera GateLPR started as a HomeKit Camera RTP Stream Management (Experimental)
   HomeKit Bridge Debug            Indigo device B
```

**Comment by Ghawken** [comment]
Line 4383:

Is this right?  Should be the Other way around?
```
						if biPass != "":
							biURL = u"http://{}:{}".format(biServerIp, biPort)
						else:
							biURL = u"http://{}:{}@{}:{}".format(biUser, biPass, biServerIp, biPort)
```
Changed to biPass ="";
Seems to have fixed....
Testing a bit more now

**Comment by Colorado4Wheeler** [comment]
Check out the config folder under prefs, open the config.json and see if those urls are correct and work in a browser.

**Comment by Colorado4Wheeler** [comment]
If they are then also check the Homebridge log and see if it’s complaining.

**Comment by Ghawken** [comment]
Did you see this?
Line 4383:

Is this right?  Should be the Other way around?
```
						if biPass != "":
							biURL = u"http://{}:{}".format(biServerIp, biPort)
						else:
							biURL = u"http://{}:{}@{}:{}".format(biUser, biPass, biServerIp, biPort)
```
Changed to biPass ="";


Checked URLs in Config

images should be image
eg.
`http://test:passwoprd5@192.168.1.208:801/image/Drv2?w=1920 `

**Comment by Colorado4Wheeler** [comment]
Yup, it should

**Comment by Ghawken** [comment]
Almost there!

Also temp.h264 works with great stream if changed to temp.m  (which is apple/ios streaming default)

The 264 - worked but very blurry, low framerates - this one temp.m  seems perfect!

**Comment by Colorado4Wheeler** [comment]
Ok, I’ll patch tomorrow and maybe we’ll have it.

**Comment by Colorado4Wheeler** [comment]
What url is used for the temp?

**Comment by Ghawken** [comment]
Great.  Good work.  I'll keep testing a bit - and update here for (your) tomorrow!
Glenn

**Comment by Ghawken** [comment]
http://test:password5@192.168.1.208:801/h264/Drv2/temp.m
**Video Stream**
http://test:password5@192.168.1.208:801/image/Drv2?w=1920
**Image Stream**

**Comment by Ghawken** [comment]
Finally: Bump to above:  Morning!  (When you get this)

This is what I have now got (with updated ffmpeg) in obvious lines (4361)
Probably should look at a pull - but then that would presume I have had any significant input - when not at all!

```
				if r["hktype"] == "service_CameraRTPStreamManagement" and indigo.devices[int(r["id"])].pluginId == "com.GlennNZ.indigoplugin.BlueIris":
					biDev = indigo.devices[int(r["id"])]
					biWidth = biDev.states["width"]
					biHeight = biDev.states["height"]
					biName = biDev.states["optionValue"]
					biFPS = biDev.states["FPS"]
					biAudio = biDev.states['audio']
					if biFPS == 0: biFPS = 30
					biURL = ""
					
					# Read the Blue Iris preferences file
					prefFile = '{}/Preferences/Plugins/com.GlennNZ.indigoplugin.BlueIris.indiPref'.format(indigo.server.getInstallFolderPath())
					
					if os.path.isfile(prefFile):
						file = open(prefFile, 'r')
						prefdata = file.read()
						dom = xml.dom.minidom.parseString(prefdata)	
						prefs = self._getChildElementsByTagName(dom, u"Prefs")
						biServerIp = self._getElementValueByTagName(prefs[0], u"serverip", required=False, default=u"")
						biPort = self._getElementValueByTagName(prefs[0], u"serverport", required=False, default=u"")
						biUser = self._getElementValueByTagName(prefs[0], u"serverusername", required=False, default=u"")
						biPass = self._getElementValueByTagName(prefs[0], u"serverpassword", required=False, default=u"")
						
						if biPass == "":
							biURL = u"http://{}:{}".format(biServerIp, biPort)
						else:
							biURL = u"http://{}:{}@{}:{}".format(biUser, biPass, biServerIp, biPort)
							
						file.close()
							
					if biURL != "":						
						camera = {}	
						videoConfig = {}
					
						videoConfig["source"] = u"-re -i {}/h264/{}/temp.m".format(biURL, biName)
						videoConfig["stillImageSource"] = u"-i {}/image/{}".format(biURL, biName)
						videoConfig["maxWidth"] = biWidth
						videoConfig["maxHeight"] = biHeight
						videoConfig["maxFPS"] = biFPS		
						videoConfig['maxStreams'] = 2

						if biAudio == True:
							videoConfig['audio'] = True
						else:
							videoConfig['audio'] = False

						#videoConfig['debug'] = True
						videoConfig['maxBitrate'] = 1500

						camera["name"] = r["alias"]
						camera["videoConfig"] = videoConfig
					
						cameras.append(camera)	
```

**Comment by Highsteads** [comment]
Morning Glenn, 

Never had 'Fireworks' before :)

Followed each bit above, then found you wrapped it all up in the post above.

I have updated 0.19.7 to your code (but I have not updated the 'Need FFMPEG version that has been encoded with 'libfdk_aac' bit as not sure what and where to put the files.

I still get a 2 minute timeout but everything else is fine and now I get a live picture in 10 seconds compared to 20-30 seconds and the picture now updates every 10 seconds instead of just counting up 1m ago, 2m ago, 3m ago.

Having now looked inside the plugin with BBEdit I am just blown away with the size of it. 
Just amazing C4W!!!!!, you need the fireworks. 
Clive_S

**Comment by Colorado4Wheeler** [comment]
Holy cow, this (and the slew of new issues) is a lot to digest first thing in the morning!  I'll do some updates this morning to see how they work, but the sound thing I'm leaving to Webdeck to do since he did the FFMPEG distro - stability is critical for me and I don't want to build outside of the original project for this.  Glad you got it working though, I know that audio was an issue before.

**Comment by Colorado4Wheeler** [comment]
This part is redundant because it defaults to 2 streams already:
   
     videoConfig['maxStreams'] = 2

**Comment by Colorado4Wheeler** [comment]
Ok, the new recommended settings will be in 19.8.

**Comment by Colorado4Wheeler** [comment]
The new release is up, see how that works.

**Comment by Highsteads** [comment]
Updated to 19.8, all working but after about 2 minutes the live stream gives the No response-camera not responding.
Anything I can test, change,log that will help?

Clive_S

**Comment by Highsteads** [comment]
Well now that I actually have changed the correct settings (I was changing the camera bit rate on the camera itself!!!.. idiot) in the HK Bridge it lasts longer than 2 minutes, I took it down to 300.
I cannot say for certain as until my new Dahua camera arrives tomorrow I have a very temperamental Hikvision at present that goes awol at times.

**Comment by Colorado4Wheeler** [comment]
Yea, when I took my bitrate to 1500 my SecuritySpy server didn't like it, all the cameras in HomeKit started cutting in and out quite bad - but when I knocked it back down to 300 it was doing much better.

**Comment by Ghawken** [comment]
Morning all!
Thanks for the changes - can confirm working well (once replaced the ffmpeg with audio compatible version linked above) 
The bitrate setting is interesting - LAN connection 1500 is fine, WAN connection crappy and even quite lower connection problem with eventually dropping.  BI does options of which streaming profile to use (with various settings) I'll see if I can find url to access/change.
Glenn

**Comment by Colorado4Wheeler** [comment]
Yea, that’s why I didn’t want to hard-code 1500 frame rate, that can be a killer remotely, better to have an option for it instead.  Glad it’s working!  Audio will be in the future builds, just not default yet.

**Comment by Ghawken** [comment]
Great.  

Have found that BI always uses streaming 0 encoder profile for the url links.  Mine is obviously set at high bitrate will adjust and test. 
`The video stream appears to always use the Streaming 0 encoder profile that you can set up in Blue Iris Options > Web server.`

Ideally this and the maxBitRate should match I would think.  Might be able to pull this info and add to BI server device.  Either way manually they can be adjusted to being similar I would assume - but will TEST!

Glenn

**Comment by Colorado4Wheeler** [comment]
It’s all a step in the right direction.  I think we are 99% of the way there, just a bit of fine tuning to make it optimal, but even without that fine tuning it’s quite functional.

**Comment by Ghawken** [comment]
Back to this ‘Issue’

Well done on your very productive complications progress.  One thing i can say is HomeKit stands up to multiple and I mean multiple restarts!

I have been testing, trying, testing..

Went right back to decoding all streams, trying to make as compatible as possible.   
That works fine, unless on WAN - in which case just get static image updated every few minutes only.

Disabled audio - as the temp.m file is a mpegts which causes some issues (this is only stream that has audio).  Discovered with some network tracing some undocumented url to get access to BI different stream settings - 0,1,2 streams selectable.  Also found seperate per camera audio streams.  The new one video/cam name/2.0?stream=#-  Is a raw h264 stream without audio - can mux another stream/input in but then ffmpeg.js has to be BlueIris specific/changes there.

Tried every possible combination that made sense - and on low bandwidth settings just doesn’t work.  For some reason fails to re-encode - if I change to direct stream copy works much better - but then the BI server bandwidth settings need to be match and be low  (no re-encoding)

As you can gather this was a bit frustrating - finally a few minutes ago rebuild ffmpeg with openh264 library as well as few other options .  Tried this instead of libx264 - and bang!  The low bandwidth stream actually plays - look dreadful as it’s only 132k - but it plays!  Problem all along was some incompatiblity with BI h264 stream and libx264 - or some setting I didn’t try.

Think this means if avoid audio - can select vcodec to use within plugin.py and most of the settings will be there.  Does need ffmpeg build with openh264 though - I think this also resolve a few ffmpeg-HomeKit stream issues and I’ll report back there!

Glenn

**Comment by Colorado4Wheeler** [comment]
> One thing i can say is HomeKit stands up to multiple and I mean multiple restarts!

That's hit and miss.  For some reason I lost every single room assignment and all my automation and most of my scenes for just one HB server - which happened to be a full 90 device server, and it correlated to my having my HomeKit Bridge servers down for hours on end while testing complications yesterday.  Very frustrating.

> As you can gather this was a bit frustrating

Just a reminder: this is a home automation app 😉.  I think the discoveries you are making are actually really cool and I'm pretty floored by your ability to tweak this home automation app into a security monitor but I can't help but to think that every time I release an update you have to overwrite the Homebridge integration to resume your project.  😳

**Comment by Colorado4Wheeler** [comment]
Glenn,

The next release of HKB will include 0.1.8 of Camera-FFMPEG.  They have made some changes to the command line options and a few other things that may be of interest to you.  I thought that since you have become the resident expert on that package you might want to [browse the commits since 0.1.7](https://github.com/KhaosT/homebridge-camera-ffmpeg/commit/a7c943000eac32056da15cf9d5f9438ca6df529c) and see if there are any changes you think should be made to the command line sent from Homebridge to FFMPEG.

**Comment by Ghawken** [comment]
Hi - thanks for the words of support!

Did upgrade to 0.1.8 a while ago - with a couple of command lline changes and also moving some error logging out.  
The additionalCommandline option - defaults to zerolatency tuning but depends on what suits camera.  You may find for SecuritySpy a different commandline option is better?

With BI:
I have moved towards copying the stream completely and encoding audio to OPUS (avoids needing lib-fdkaac) Still jittering audio but better and doesn't stuff up the video stream.  

I should fork the ffmpeg code and issue a pull for a couple of changes: Probably option to copy video stream, and option to add more detailed logging with -loglevel if debug is on.  

Presumably these changes would then work there way to you and later down the track could add plugin option to copy or decode stream for each device?
