### ISSUE TITLE
Aeon Labs Multisensor Temperature Displayed Incorrectly

### ISSUE THREAD

**Issue by grwilde** [Colorado4Wheeler/HomeKit-Bridge#69]
I created HomeKit Devices for my several Aeon Labs Multisensors to display motion, temperature, humidity, and luminosity. The motion detection devices show correctly, and the humidity and luminosity values display correctly in the Home App. The temperature values, however, are incorrect. I have set the server to Fahrenheit which is the setting of the Multisensors. The temperature values displayed in Indigo are correct and in Fahrenheit (for example 67.9). The values displayed in the Home App are incorrect (for example 154). The difference indicates that the sensor temperature (already in Fahrenheit) was assumed to be in Celsius and therefore converted to Fahrenheit (i.e.; 67.9*(9/5) + 32 = 154).

**Comment by Colorado4Wheeler** [comment]
Please post the results from [Simulate HomeKit For Server Item](https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#simulate-homekit-for-server-item) so I can see.  If it's converting then I think one of your config settings may be backwards.  There are **two** settings for temperature, one is in the server config and the other is when you config the device there is a checkbox that says "Temperature is in Fahrenheit" and if this is NOT checked then it will assume it's Celsius and pass it to HomeKit without converting.

**Comment by grwilde** [comment]
Sorry about that. I didn't see the individual device temperature settings. I checked the "Temperature is in Fahrenheit" boxes and now the displayed temperatures are correct.

**Comment by Colorado4Wheeler** [comment]
Woot!
