### ISSUE TITLE
DSC Alarm Partition 3 Always showing as 'Home'

### ISSUE THREAD

**Issue by durosity** [Colorado4Wheeler/HomeKit-Bridge#71]
I've just added my DSC Alarm Partition 3 for my shed to HKB but unlike the two other partitions for the home and garage it just sits with a status of Home and if i try to change it it just spins perpetually.  Simulation dump below.  Oddly i'm not seeing anything about why it'd see it as Home.  

	   HomeKit Bridge                  Simulating HomeKit values for Alarm - Control Panel (Partition 3 - Shed)
	   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
	   HomeKit Bridge                  address : 
	batteryLevel : None
	buttonGroupCount : 0
	configured : True
	description : 
	deviceTypeId : alarmKeypad
	displayStateId : state
	displayStateImageSel : None
	displayStateValRaw : disarmed
	displayStateValUi : disarmed
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 1862834123
	globalProps : MetaProps : (dict)
		 com.frightideas.indigoplugin.dscAlarm : (dict)
			  partitionName : Shed (string)
			  partitionNumber : 3 (string)
	id : 894749546
	lastChanged : 2018-03-19 10:42:12
	lastSuccessfulComm : 2018-03-19 10:42:12
	model : Alarm Keypad
	name : Alarm - Control Panel (Partition 3 - Shed)
	ownerProps : com.frightideas.indigoplugin.dscAlarm : (dict)
		 partitionName : Shed (string)
		 partitionNumber : 3 (string)
	pluginId : com.frightideas.indigoplugin.dscAlarm
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Plugin
	remoteDisplay : True
	states : States : (dict)
		 ArmedState : 0 (integer)
		 ArmedState.away : false (bool)
		 ArmedState.disarmed : false (bool)
		 ArmedState.stay : false (bool)
		 KeypadChime : 0 (integer)
		 KeypadChime.disabled : false (bool)
		 KeypadChime.enabled : false (bool)
		 LCDLine1 :   Date     Time  (string)
		 LCDLine2 : MAR 19/18 10:43a (string)
		 LEDArmed : off (on/off bool)
		 LEDBypass : off (on/off bool)
		 LEDMemory : off (on/off bool)
		 LEDReady : off (on/off bool)
		 LEDTrouble : off (on/off bool)
		 PanicState : none (string)
		 PanicState.ambulance : false (bool)
		 PanicState.duress : false (bool)
		 PanicState.fire : false (bool)
		 PanicState.none : true (bool)
		 PanicState.panic : false (bool)
		 ReadyState : ready (string)
		 ReadyState.notready : false (bool)
		 ReadyState.ready : true (bool)
		 state : disarmed (string)
		 state.armed : false (bool)
		 state.disarmed : true (bool)
		 state.entryDelay : false (bool)
		 state.exitDelay : false (bool)
		 state.tripped : false (bool)
	subModel : 
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsStatusRequest : False
	version : None
	   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
	   HomeKit Bridge                  Service : 
		alias : Alarm - Control Panel (Partition 3 - Shed)
		model : 
		subModel : 
		indigoType : indigo.Device
		pluginType : indigo.Device.com.frightideas.indigoplugin.dscAlarm.alarmKeypad
		type : SecuritySystem
		desc : Security System
		objId : 894749546
		serverId : 0
		invertOnState : False
		convertFahrenheit : False
		required : (List)
			SecuritySystemTargetState : 0
			SecuritySystemCurrentState : 0
		optional : (List)
			StatusTampered
			StatusFault
			SecuritySystemAlarmType
			Name
		native : True
		requiresPlugin : (List)
		actions : (List)
		loadOptional : False
		characterDict : (Dict)

**Comment by Colorado4Wheeler** [comment]
I'm not sure if you chopped off the bottom of the dump or if characterDict was really empty but looking at the code there should be no reason for that.  Keypads have been working so for one to get singled out is suspicious.  

I've been using the ArmedState states rather than the state states for the current state of the alarm, not sure if that's correct or not - but even if it's wrong those characteristics should be there, as should be at least four conditional actions.

**Comment by Colorado4Wheeler** [comment]
Just a bump, please double check that output to see if it was chopped off.  The definition I have clearly defines that make and model so there's no reason it should be missing so much information that i can think of.

**Comment by durosity** [comment]
Just did it again, looks like it's identical to my original post.  I'll post a partition that's working after this in case it's relevant.  

   HomeKit Bridge                  Simulating HomeKit values for Alarm - Control Panel (Partition 3 - Shed)
   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
   HomeKit Bridge                  address : 
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : alarmKeypad
displayStateId : state
displayStateImageSel : None
displayStateValRaw : disarmed
displayStateValUi : disarmed
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1862834123
globalProps : MetaProps : (dict)
     com.frightideas.indigoplugin.dscAlarm : (dict)
          partitionName : Shed (string)
          partitionNumber : 3 (string)
id : 894749546
lastChanged : 2018-03-22 13:38:32
lastSuccessfulComm : 2018-03-22 13:38:32
model : Alarm Keypad
name : Alarm - Control Panel (Partition 3 - Shed)
ownerProps : com.frightideas.indigoplugin.dscAlarm : (dict)
     partitionName : Shed (string)
     partitionNumber : 3 (string)
pluginId : com.frightideas.indigoplugin.dscAlarm
pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     ArmedState : 0 (integer)
     ArmedState.away : false (bool)
     ArmedState.disarmed : false (bool)
     ArmedState.stay : false (bool)
     KeypadChime : 0 (integer)
     KeypadChime.disabled : false (bool)
     KeypadChime.enabled : false (bool)
     LCDLine1 :   Date     Time  (string)
     LCDLine2 : MAR 22/18  1:38p (string)
     LEDArmed : off (on/off bool)
     LEDBypass : off (on/off bool)
     LEDMemory : off (on/off bool)
     LEDReady : off (on/off bool)
     LEDTrouble : off (on/off bool)
     PanicState : none (string)
     PanicState.ambulance : false (bool)
     PanicState.duress : false (bool)
     PanicState.fire : false (bool)
     PanicState.none : true (bool)
     PanicState.panic : false (bool)
     ReadyState : ready (string)
     ReadyState.notready : false (bool)
     ReadyState.ready : true (bool)
     state : disarmed (string)
     state.armed : false (bool)
     state.disarmed : true (bool)
     state.entryDelay : false (bool)
     state.exitDelay : false (bool)
     state.tripped : false (bool)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None
   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
   HomeKit Bridge                  Service : 
	alias : Alarm - Control Panel (Partition 3 - Shed)
	model : 
	subModel : 
	indigoType : indigo.Device
	pluginType : indigo.Device.com.frightideas.indigoplugin.dscAlarm.alarmKeypad
	type : AirPurifier
	desc : Air Purifier
	objId : 894749546
	serverId : 0
	invertOnState : False
	convertFahrenheit : False
	required : (List)
		Active : 0
		TargetAirPurifierState : 0
		CurrentAirPurifierState : 0
	optional : (List)
		LockPhysicalControls
		RotationSpeed
		Name
		SwingMode
	native : True
	requiresPlugin : (List)
	actions : (List)
	loadOptional : False
	characterDict : (Dict)

**Comment by durosity** [comment]
22 Mar 2018, 13:41:45
   HomeKit Bridge                  Simulating HomeKit values for Alarm - Control Panel (Partition 1 - House)
   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
   HomeKit Bridge                  address : 
batteryLevel : None
buttonGroupCount : 0
configured : True
description : DSC Alarm - Main House
deviceTypeId : alarmKeypad
displayStateId : state
displayStateImageSel : None
displayStateValRaw : disarmed
displayStateValUi : disarmed
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1862834123
globalProps : MetaProps : (dict)
     com.frightideas.indigoplugin.dscAlarm : (dict)
          partitionName : House (string)
          partitionNumber : 1 (string)
id : 1091013919
lastChanged : 2018-03-22 13:41:32
lastSuccessfulComm : 2018-03-22 13:41:32
model : Alarm Keypad
name : Alarm - Control Panel (Partition 1 - House)
ownerProps : com.frightideas.indigoplugin.dscAlarm : (dict)
     partitionName : House (string)
     partitionNumber : 1 (string)
pluginId : com.frightideas.indigoplugin.dscAlarm
pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     ArmedState : disarmed (string)
     ArmedState.away : false (bool)
     ArmedState.disarmed : true (bool)
     ArmedState.stay : false (bool)
     KeypadChime : 0 (integer)
     KeypadChime.disabled : false (bool)
     KeypadChime.enabled : false (bool)
     LCDLine1 :   Date     Time  (string)
     LCDLine2 : MAR 22/18  1:41p (string)
     LEDArmed : off (string)
     LEDBypass : off (string)
     LEDMemory : off (string)
     LEDReady : on (string)
     LEDTrouble : off (string)
     PanicState : none (string)
     PanicState.ambulance : false (bool)
     PanicState.duress : false (bool)
     PanicState.fire : false (bool)
     PanicState.none : true (bool)
     PanicState.panic : false (bool)
     ReadyState : ready (string)
     ReadyState.notready : false (bool)
     ReadyState.ready : true (bool)
     state : disarmed (string)
     state.armed : false (bool)
     state.disarmed : true (bool)
     state.entryDelay : false (bool)
     state.exitDelay : false (bool)
     state.tripped : false (bool)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None
   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
   HomeKit Bridge                  Service : 
	alias : Alarm - Control Panel (Partition 1 - House)
	model : 
	subModel : 
	indigoType : indigo.Device
	pluginType : indigo.Device.com.frightideas.indigoplugin.dscAlarm.alarmKeypad
	type : SecuritySystem
	desc : Security System
	objId : 1091013919
	serverId : 0
	invertOnState : False
	convertFahrenheit : False
	required : (List)
		SecuritySystemTargetState : 0
		SecuritySystemCurrentState : 0
	optional : (List)
		StatusTampered
		StatusFault
		SecuritySystemAlarmType
		Name
	native : True
	requiresPlugin : (List)
	actions : (List)
	loadOptional : False
	characterDict : (Dict)

**Comment by Colorado4Wheeler** [comment]
That's interesting, I just did a search and there must be something different about this particular device because it's not the same as the other keypad I had added support for

**Comment by durosity** [comment]
Ah, that's interesting cos it works for partition 1 and partition 2.  I'm connecting to the panel using an IT-100 serial connection rather than an envisalink but i wouldn't have thought that'd make a material impact on the state of the control panel.  I do have an Envisalink 4 that i previously used with Homebridge-Envisalink so i could test with that if you'd like.

**Comment by Colorado4Wheeler** [comment]
No, it is.  I don't understand.  Grrr.  Rabbit holes... ;)

**Comment by durosity** [comment]
![image](https://user-images.githubusercontent.com/17961550/37774129-52645d70-2dd7-11e8-995f-4338f3ee3236.png)

**Comment by Colorado4Wheeler** [comment]
What I coded before was for ArmedState, is this one not using that and uses something else?  Does the keypad use one or the other depending on a setting?  if that's the case then I may not be able to support this until complications because I **know** it was working before.

**Comment by Colorado4Wheeler** [comment]
This is THE problem with coding for things I don't have, I can't test and it get so frustrating to diagnose something that I don't understand how it works.  Partition 1 and partition 2?  What's that even mean and how is that reflected in the devices?  Whats the device difference?

**Comment by Colorado4Wheeler** [comment]
Now you understand why Matt & Jay have to purchase every Zwave device and Insteon device under the sun in order to build support for it ;).

**Comment by durosity** [comment]
As best i'm aware it should work identically to partition 1 and 2.

Partitions are different areas of a location, in my case i have 3 - one for the main house, one for the garage, and one for the shed.  You can set each one to different armed states, eg the house can be disarmed but the garage and shed may be set in away mode.  This would mean if someone tried to open the shed it'd still trigger an alarm, but at the same time i can be freely walking around the house not tripping the alarm!  

And yes.. i'm fully aware of the pains they go through (including different firmware versions, etc).  I've done quite a lot of testing for this kinda thing in previous jobs and seen the headaches that developers have, hehe!  (of course back then i was more technically capable.. these days my mind is much more clouded and i find it impossible to do things i could do 10 years ago.  

I'm at work at the moment but when i get home this evening i'm gonna go through and document everything i can regarding the panels.  I'll do data dumps of them each in their respective states.

**Comment by Colorado4Wheeler** [comment]
I think the only thing I really need is to see a working partition and a non working partition so I can try to figure out what the difference is.  It makes no sense that the location of the item on your property would change whether or not the plugin works, that's insane, there's something else.

According to my code it's saying everything is based on 'ArmedState' and 'tripped' for a security device, so I'm looking at 'ArmedState.disarmed' being true or 'ArmedState.stay' being true or 'ArmedState.away' being true or 'state.tripped' being true to tell HomeKit what the device is.

**Comment by durosity** [comment]
OH.  UPDATE:

I've just had a bit of a sniff around.. looks like partition 3 on my panel is spitting out errors of some kind.  I'll investigate when i get home.  In the mean time stand down :D

**Comment by durosity** [comment]
Oh dear.  It's happening all over the place now.  Time for a power cycle of the panel.

**Comment by Colorado4Wheeler** [comment]
LOL, so we might have been chasing a gremlin on your end rather than a bug on mine?

**Comment by durosity** [comment]
Possibly.  Although why it still worked for P1 and P2 i'm not sure.  I'll reboot it tonight and see what happens... of course that involves climbing into my loft and on this dodgy foot of mine that could be fun.

**Comment by durosity** [comment]
(And also of interest the DSC Plugin isn't reporting any errors at all.  It's even still updating the time correctly and that comes directly from the panel)

**Comment by Colorado4Wheeler** [comment]
What's the status of this issue?  Resolved after you reset your DSC this past weekend?

**Comment by durosity** [comment]
I’ve not finished the rebuild yet, just the basics.  Hopefully 100% rebuilt this eastern weekend.

**Comment by Colorado4Wheeler** [comment]
Ahh, Easter: Ham, Twice Baked Potatoes, Strawberry Shortcake and DSC alarm panel rebuilds.  Tradition is awesome.

**Comment by durosity** [comment]
For me it’s more often sugar coma from too many Easter eggs.. and DSC panel rebuilds.  (I did actually spend last Easter doing that too but that was due to an upgrade from a 32 zone panel to a 64 zone one)

**Comment by Colorado4Wheeler** [comment]
Did you have a chance to figure this one out yet?

**Comment by durosity** [comment]
No, every time I reenable that partition the panel locks up.  I’m suspect I’m gonna have to replace the board, only problem is what I thought was a replacement board is actually a 32 zone.. so I’m gonna have to order a replacement.  Joy.  I’ll close the issue and re open it if it persists when it’s fixed.

**Comment by Colorado4Wheeler** [comment]
Yikes.  Good luck!
