### ISSUE TITLE
MQTT Devices

### ISSUE THREAD

**Issue by rlust** [Colorado4Wheeler/HomeKit-Bridge#74]
I am using the MQTT device plugin for ESP8266 devices. They are showing up as Motion Detectors.

Did I miss a way to change the device type?

GREAT PLUGIN!

**Comment by Colorado4Wheeler** [comment]
Likely.  Did you [read the section about adding devices and actions in the Wiki](https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Server-Device#device--action)?  You'll see on the screenshot and in the manual that there's a HomeKit type as a field there before you click `Add To HomeKit`.
