### ISSUE TITLE
Very Intermittent Homebridge Hangs

### ISSUE THREAD

**Issue by Colorado4Wheeler** [Colorado4Wheeler/HomeKit-Bridge#76]
This has happened two or three times since the very start of the project, so it's not very often, but I've noticed that sometimes Homebridge can hang and just stop responding.  This happened last night when my HomePod kept telling me that it couldn't reach HomeKit no matter what I asked it to do.  When I looked at my iOS device every device on every server showed "No response" and I thought maybe I was having an issue like #70 did yesterday with a blow up, but I noticed that my Hue bulbs were just fine.  Restarting the plugin, which in turn forces a restart of Homebridge, solved the issue instantly.  I checked that the API was still answering at it was, just Homebridge crapped out.

I don't recall ever having this problem with the original HB builds but I don't know that I had so many running at once either (I run 8 servers right now), but I suspect there might be something that may be puking in the script but it's not often enough to be a major issue at this point.

**Comment by webdeck** [comment]
Please provide the homebridge.log file when it hangs.
