### ISSUE TITLE
Temperature, humidity and luminosity sensor display

### ISSUE THREAD

**Issue by berkinet** [Colorado4Wheeler/HomeKit-Bridge#77]
I have several temperature sensors, of different types. But, all are created in Indigo as devices and display the current temp in Celsius as the states "state" and "temperature." HomeKit Bridge Server Option is set as "Thermostats are Celsius." However, in HomeKit, all the temps display as -1.0 I have the same issue with humidity and light sensors.

**Comment by Colorado4Wheeler** [comment]
Please [Simulate For Server Item](https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#simulate-homekit-for-server-item) and post the results so I can see how HomeKit is seeing this device.

**Comment by berkinet** [comment]
20 Mar 2018 at 17:28:59
   HomeKit Bridge                  Simulating HomeKit values for Bergerie temp
   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
   HomeKit Bridge                  address : Bergerie InterfaceKit |a 0
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : phIfKitSensor
displayStateId : state
displayStateImageSel : None
displayStateValRaw : 12.7
displayStateValUi : 12.7
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1986007202
globalProps : MetaProps : (dict)
     com.perceptiveautomation.indigoplugin.Phidgets : (dict)
          address : Bergerie InterfaceKit |a 0 (string)
          buttonFlagSensor : false (bool)
          cVal1 :  (string)
          cVal2 :  (string)
          decimalPlaces : 1 (string)
          phIfKitSensorModel : 1125t (string)
          phSensorIfKitAnalogInput : 0 (string)
          phSensorIfKitId : 1985707067 (string)
          phSensorIfKitSerial : 338124 (string)
          phTemp1 : cel (string)
id : 752380798
lastChanged : 2018-03-20 16:39:53
lastSuccessfulComm : 2018-03-20 16:39:53
model : InterfaceKit Sensor
name : Bergerie temp
ownerProps : com.perceptiveautomation.indigoplugin.Phidgets : (dict)
     address : Bergerie InterfaceKit |a 0 (string)
     buttonFlagSensor : false (bool)
     cVal1 :  (string)
     cVal2 :  (string)
     decimalPlaces : 1 (string)
     phIfKitSensorModel : 1125t (string)
     phSensorIfKitAnalogInput : 0 (string)
     phSensorIfKitId : 1985707067 (string)
     phSensorIfKitSerial : 338124 (string)
     phTemp1 : cel (string)
pluginId : com.perceptiveautomation.indigoplugin.Phidgets
pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     lastUpdate : 2018-03-20 16:39:53 (string)
     state : 12.7 (real)
     temperature : 12.7 (real)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None
   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
   HomeKit Bridge                  Service : 
	alias : Bergerie temp
	model : 
	subModel : 
	indigoType : indigo.Device
	pluginType : indigo.Device.com.perceptiveautomation.indigoplugin.Phidgets.phIfKitSensor
	type : TemperatureSensor
	desc : Temperature Sensor
	objId : 752380798
	serverId : 1108605555
	invertOnState : False
	convertFahrenheit : False
	required : (List)
		CurrentTemperature : 0.0
	optional : (List)
		StatusActive
		StatusFault
		StatusTampered
		Name
		StatusLowBattery : 0
	native : True
	requiresPlugin : (List)
	actions : (List)
	loadOptional : False
	characterDict : (Dict)
		CurrentTemperature : 0.0

**Comment by Colorado4Wheeler** [comment]
This is an unsupported plugin temperature sensor.  If it were a sensor device in Indigo or even an on/off or dimmable device in Indigo it would work, but because it's a custom device there is no support built in.  I'm not doing plugin devices at this point because I would end up coding the plugin in perpetuity trying to support every custom device any plugin creates.  

There is a plan to handle these types of devices in the future but we aren't there yet.  In the meantime you can try using Masquerade or even Homebridge Buddy Wrappers and you can most certainly get this into HomeKit Bridge.

**Comment by berkinet** [comment]
Thanks. Makes sense. Did I miss that limitation in the wiki?

**Comment by Colorado4Wheeler** [comment]
Yes and no, [it's in the FAQ](https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/FAQ#can-i-customize-the-way-that-indigo-devices-get-mapped-to-homekit-devices).

**Comment by berkinet** [comment]
Masquerade worked.  Though, not straight away.  I had to quit and restart the Home app before it got the temp .  Thanks

**Comment by Colorado4Wheeler** [comment]
WOOT!

**Comment by Colorado4Wheeler** [comment]
I'll leave this open as a future enhancement when the custom device definitions are coded in.

**Comment by Colorado4Wheeler** [comment]
I'll probably add this to the next release since I'm doing some plugin coding.  **Probably** being the operative word here :).

**Comment by berkinet** [comment]
Thanks. But, don't rush it for me, I am getting on fine with Masquerade.  Though, if you do add it, I will certainly test it for you.

One other question... Do you know if there is there a HomeKit service for energy monitors?

Richard

**Comment by Colorado4Wheeler** [comment]
There isn’t yet, but it’s being looked at.

**Comment by Colorado4Wheeler** [comment]
This temperature sensor is supported in the next 1.0.2 release (after the current beta 3)
