### ISSUE TITLE
Garage Door control oddity

### ISSUE THREAD

**Issue by berkinet** [Colorado4Wheeler/HomeKit-Bridge#78]
I have created a Virtual Device that operates a momentary contact Action to control the gate. To track the state of the gate, I have a variable setup. Its value is either open or closed. The Virtual Device interprets closed as off and open as on. Basically, I am simulating successive presses on a single button remote control. In HKB I have selected the Virtual Device as a Garage Door and called it the gate and set the state as inverted. In general it works, except, whenever I restart HKB, the gate in HK changes its state to open, even though the Virtual Device is off and the gate is closed. I used the garage door so I can say "open the gate" I think the HK service should startup in the right state but can't seem to get it to do that.

**Comment by Colorado4Wheeler** [comment]
Please [Simulate For Server Item](https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#simulate-homekit-for-server-item) and post the results so I can see how HomeKit is seeing this device.  Do this for when it's working and when it is not working so I can see the difference between the two.

**Comment by berkinet** [comment]
20 Mar 2018 at 17:29:17
   HomeKit Bridge                  Simulating HomeKit values for Front Gate
   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
   HomeKit Bridge                  address : 
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : pseudoRelay
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1996529970
globalProps : MetaProps : (dict)
     com.perceptiveautomation.indigoplugin.devicecollection : (dict)
          doToggle : false (bool)
          executionType : actionGroup (string)
          offActionGroup : 1662828976 (string)
          onActionGroup : 1662828976 (string)
          statusRequestActionGroup :  (string)
          statusVariable : 459761069 (string)
          supportsStatusRequest : true (bool)
          toggleActionGroup :  (string)
id : 1718387248
lastChanged : 2018-03-20 17:14:03
lastSuccessfulComm : 2018-03-20 17:14:03
ledStates : []
model : Virtual On/Off Device
name : Front Gate
onState : False
ownerProps : com.perceptiveautomation.indigoplugin.devicecollection : (dict)
     doToggle : false (bool)
     executionType : actionGroup (string)
     offActionGroup : 1662828976 (string)
     onActionGroup : 1662828976 (string)
     statusRequestActionGroup :  (string)
     statusVariable : 459761069 (string)
     supportsStatusRequest : true (bool)
     toggleActionGroup :  (string)
pluginId : com.perceptiveautomation.indigoplugin.devicecollection
pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     onOffState : off (on/off bool)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None
   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
   HomeKit Bridge                  Service : 
	alias : Front Gate
	model : 
	subModel : 
	indigoType : indigo.RelayDevice
	pluginType : indigo.RelayDevice.com.perceptiveautomation.indigoplugin.devicecollection.pseudoRelay
	type : GarageDoorOpener
	desc : Garage Door Opener
	objId : 1718387248
	serverId : 1108605555
	invertOnState : True
	convertFahrenheit : False
	required : (List)
		ObstructionDetected : False
		TargetDoorState : 1
		CurrentDoorState : 1
	optional : (List)
		LockTargetState
		Name
		LockCurrentState
	native : True
	requiresPlugin : (List)
	actions : (List)
		Action : (HomeKitAction)
			Characteristic : TargetDoorState
			When : equal
			Value : 0 (int)
			Value2 : 0 (int)
			Command : device.turnOn
			Arguments : [1718387248]
			monitors : {1718387248: 'attr_onState'}
		Action : (HomeKitAction)
			Characteristic : TargetDoorState
			When : equal
			Value : 1 (int)
			Value2 : 0 (int)
			Command : device.turnOff
			Arguments : [1718387248]
			monitors : {1718387248: 'attr_onState'}
		Action : (HomeKitAction)
			Characteristic : CurrentDoorState
			When : equal
			Value : 0 (int)
			Value2 : 0 (int)
			Command : device.turnOn
			Arguments : [1718387248]
			monitors : {1718387248: 'attr_onState'}
		Action : (HomeKitAction)
			Characteristic : CurrentDoorState
			When : between
			Value : 1 (int)
			Value2 : 4 (int)
			Command : device.turnOff
			Arguments : [1718387248]
			monitors : {1718387248: 'attr_onState'}
	loadOptional : False
	characterDict : (Dict)
		ObstructionDetected : False
		TargetDoorState : 1
		CurrentDoorState : 1

**Comment by Colorado4Wheeler** [comment]
Is that the working state or the not working state?  Whichever it is can you please also post the opposite so I can compare?

**Comment by berkinet** [comment]
It only had the wrong state on restart. Just tried restarting and wouldn't you know it, it worked.  I'll watch for the error and try to capture the device data

**Comment by Colorado4Wheeler** [comment]
One of the things you may be dealing with on this and the other device that you said worked after you restarted when you added the Masquerade device is that HomeKit knows when the accessory goes down and will sort of hang for a minute, you could have been looking at the "hung" state where it defaults everything and it hadn't yet communicated with the server yet.  For me, I run into this all the time, so I created a second home so I can switch to that home and then back and the refresh will force - the 2nd home doesn't need to have any accessories, it's just a place to switch back and forth from when you want to force HomeKit to refresh.
