### ISSUE TITLE
Heatmiser Neo Thermostat doesn't respond to Home App 

### ISSUE THREAD

**Issue by IndigoColly** [Colorado4Wheeler/HomeKit-Bridge#79]
As per forum comment the thermostat doesn't respond to any set points. The log entry is as follows:

`HomeKit Bridge Error            Maximum time exceeded while setting the 'TargetTemperature' HomeKit characteristic for 'Sitting Room' (HomeKit device 'Sitting Room'), aborting attempt.  This can happen if you try to set a device to a state is is already in (i.e., turning off a device that is already off).`
I believe this successfully worked in a previous Beta version.

**Comment by Colorado4Wheeler** [comment]
If it responds to normal thermostat commands then I'm not sure why it would not work.  Please use the Advanced Plugin Actions menu option -> Device and select your server then Simulate as an action and that thermostat and post the results of that simulation here.

**Comment by castlesi** [comment]
HomeKit Bridge                  Simulating HomeKit values for Kitchen
   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
   HomeKit Bridge                  address : 0
batteryLevel : None
buttonGroupCount : 0
configured : True
coolIsOn : False
coolSetpoint : 0.0
dehumidifierIsOn : False
description : 
deviceTypeId : heatmiserNeostat
displayStateId : temperatureInputsAll
displayStateImageSel : TemperatureSensor
displayStateValRaw : 19.3
displayStateValUi : 19.3
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
fanIsOn : False
fanMode : Auto
folderId : 1335677605
globalProps : MetaProps : (dict)
     com.racarter.indigoplugin.heatmiser-neo : (dict)
          address : 0 (integer)
heatIsOn : False
heatSetpoint : 20.0
humidifierIsOn : False
humidities : []
humiditySensorCount : 0
hvacMode : ProgramHeat
id : 1615313361
lastChanged : 2018-03-22 22:03:38
lastSuccessfulComm : 2018-03-22 22:03:38
model : Heatmiser Neo Thermostat
name : Kitchen
ownerProps : com.racarter.indigoplugin.heatmiser-neo : (dict)
     address : 0 (integer)
pluginId : com.racarter.indigoplugin.heatmiser-neo
pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     Away : false (bool)
     DST_Auto : True (string)
     DST_On : False (string)
     FrostTemp : 12 (integer)
     HubFirmwareVersion : 2077 (string)
     NTP_Status : Running (string)
     Prog_Format : 7day (string)
     ROC : 97 (integer)
     SwitchDiff : 1 (integer)
     Units : degC (string)
     heatIsOn : false (bool)
     hvacFanMode : 0 (integer)
     hvacFanModeIsAlwaysOn : false (bool)
     hvacFanModeIsAuto : false (bool)
     hvacOperationMode : 4 (integer)
     hvacOperationMode.ui : program heat on (string)
     hvacOperationModeIsAuto : false (bool)
     hvacOperationModeIsCool : false (bool)
     hvacOperationModeIsHeat : false (bool)
     hvacOperationModeIsOff : false (bool)
     hvacOperationModeIsProgramAuto : false (bool)
     hvacOperationModeIsProgramCool : false (bool)
     hvacOperationModeIsProgramHeat : true (bool)
     preHeat : true (bool)
     setpointCool : 0 (integer)
     setpointHeat : 20 (real)
     temperatureInput1 : 19.3 (real)
     temperatureInput1.ui : 19.3 °C (string)
     temperatureInputsAll : 19.3 (string)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsCoolSetpoint : True
supportsHeatSetpoint : True
supportsHvacFanMode : True
supportsHvacOperationMode : True
supportsStatusRequest : True
temperatureSensorCount : 1
temperatures : [19.3]
version : None
   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
   HomeKit Bridge                  Service : 
	alias : Kitchen
	model : 
	subModel : 
	indigoType : indigo.ThermostatDevice
	pluginType : indigo.ThermostatDevice.com.racarter.indigoplugin.heatmiser-neo.heatmiserNeostat
	type : Thermostat
	desc : Thermostat
	objId : 1615313361
	serverId : 253101584
	invertOnState : False
	convertFahrenheit : False
	required : (List)
		CurrentHeatingCoolingState : 0
		TargetTemperature : 20.0
		TemperatureDisplayUnits : 0
		CurrentTemperature : 19.3
		TargetHeatingCoolingState : 1
	optional : (List)
		HeatingThresholdTemperature : 20.0
		TargetRelativeHumidity
		CoolingThresholdTemperature : 0.0
		Name
		CurrentRelativeHumidity
	native : True
	requiresPlugin : (List)
	actions : (List)
		Action : (HomeKitAction)
			Characteristic : CurrentHeatingCoolingState
			When : equal
			Value : 0 (int)
			Value2 : 0 (int)
			Command : STUB
			Arguments : [1615313361, indigo.kHvacMode.Off]
			monitors : {1615313361: 'attr_heatIsOn'}
		Action : (HomeKitAction)
			Characteristic : CurrentHeatingCoolingState
			When : equal
			Value : 0 (int)
			Value2 : 0 (int)
			Command : STUB
			Arguments : [1615313361, indigo.kHvacMode.Off]
			monitors : {1615313361: 'attr_coolIsOn'}
		Action : (HomeKitAction)
			Characteristic : TargetTemperature
			When : between
			Value : 0.0 (float)
			Value2 : 100.0 (float)
			Command : homekit.commandSetTargetThermostatTemperature
			Arguments : [1615313361, 253101584, '=value=']
			monitors : {1615313361: 'attr_heatSetpoint'}
		Action : (HomeKitAction)
			Characteristic : TargetHeatingCoolingState
			When : equal
			Value : 0 (int)
			Value2 : 0 (int)
			Command : thermostat.setHvacMode
			Arguments : [1615313361, indigo.kHvacMode.Off]
			monitors : {1615313361: 'attr_hvacMode'}
		Action : (HomeKitAction)
			Characteristic : TargetHeatingCoolingState
			When : equal
			Value : 1 (int)
			Value2 : 0 (int)
			Command : thermostat.setHvacMode
			Arguments : [1615313361, indigo.kHvacMode.Heat]
			monitors : {1615313361: 'attr_hvacMode'}
		Action : (HomeKitAction)
			Characteristic : TargetHeatingCoolingState
			When : equal
			Value : 2 (int)
			Value2 : 0 (int)
			Command : thermostat.setHvacMode
			Arguments : [1615313361, indigo.kHvacMode.Cool]
			monitors : {1615313361: 'attr_hvacMode'}
		Action : (HomeKitAction)
			Characteristic : TargetHeatingCoolingState
			When : equal
			Value : 3 (int)
			Value2 : 0 (int)
			Command : thermostat.setHvacMode
			Arguments : [1615313361, indigo.kHvacMode.HeatCool]
			monitors : {1615313361: 'attr_hvacMode'}
		Action : (HomeKitAction)
			Characteristic : HeatingThresholdTemperature
			When : equal
			Value : STUB (str)
			Value2 : 0 (str)
			Command : STUB
			Arguments : [1615313361, 0]
			monitors : {1615313361: 'attr_heatSetpoint'}
		Action : (HomeKitAction)
			Characteristic : CoolingThresholdTemperature
			When : equal
			Value : STUB (str)
			Value2 : 0 (str)
			Command : STUB
			Arguments : [1615313361, 0]
			monitors : {1615313361: 'attr_coolSetpoint'}
	loadOptional : False
	characterDict : (Dict)
		CurrentHeatingCoolingState : 0
		TargetTemperature : 20.0
		CurrentTemperature : 19.3
		TargetHeatingCoolingState : 1
		HeatingThresholdTemperature : 20.0
		TemperatureDisplayUnits : 0
		CoolingThresholdTemperature : 0.0

**Comment by Colorado4Wheeler** [comment]
This should be resolved in the next release.  I think  you are probably the first user using 'ProgramHeat' or 'ProgramCool' so this was never caught before.  You should be able to immediately use this until the next release if you want by changing it instead to just 'Heat' or 'Cool' instead of the program mode - maybe that's why it worked before.

**Comment by Colorado4Wheeler** [comment]
The latest release should resolve your issue, let me know if it does not.

**Comment by IndigoColly** [comment]
Excellent work - problem resolved.

**Comment by Colorado4Wheeler** [comment]
Awesome :).
