### ISSUE TITLE
Send Status Request Error

### ISSUE THREAD

**Issue by grwilde** [Colorado4Wheeler/HomeKit-Bridge#80]
I get the following error whenever I issue a "send status request" on each of my four HomeBridge Servers using HomeKit-Bridge-0.19.9. I discovered this error because I have a scheduled status poll of all of my devices at midnight. Other this error, the Servers appear to be functioning properly. 

   HomeKit Bridge Error            Unknown device command: actionValue : 0
configured : True
delayAmount : 900
description : unknown action type device
deviceAction : RequestStatus
deviceId : 283981199
replaceExisting : True
textToSpeak : 
   HomeKit Bridge Error            send "HomeKit Bridge" on failed

**Comment by Colorado4Wheeler** [comment]
I’m not sure where that error came from but it’s not an HKB error, you have something else doing that.  There’s no ‘textToSpeak’.  I also do not, at this time, implement a status request, what status would I be requesting if I did that?

**Comment by grwilde** [comment]
Every HomeKit Bridge Server shows on Indigo, whenever you select it, three buttons at the bottom of the page: "Turn Off", "Turn On" and "Send Status Request". If you click on "Send Status Request" you get the error shown. Many devices do not have a "Send Status Request" button (for instance your Device Extensions plugin). I suspect this is a button that has no implementation within HomeKit Bridge but somehow is displayed in Indigo.

**Comment by Colorado4Wheeler** [comment]
Resolved in the next release.
