### ISSUE TITLE
Error Message When Upgrading to HomeKit Bridge 0.20.0

### ISSUE THREAD

**Issue by grwilde** [Colorado4Wheeler/HomeKit-Bridge#81]
I am getting the following error message indicating that a camera server error has occurred when upgrading to HomeKit Bridge 0.20.0:

HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Security Cameras Bridge'.

   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Security Cameras Bridge'.

I am not sure of the significance of this message because the server does start OK and the cameras are displayed properly in the Home App.

The complete log follows:

   Stopping plugin HomeKit Bridge (pid 56329)
   HomeKit Bridge Warning          

#####################################################################
# HOMEKIT BRIDGE RUNNING SERVER SHUTDOWN                            #
#####################################################################
# Now blind stopping all running servers, due to Indigo timeout     #
# limits the plugin cannot wait for them to stop but will instead   #
# shut them down blindly and let them refresh when the plugin       #
# restarts                                                          #
#####################################################################

   HomeKit Bridge                  Blind stopping 'Environmental Bridge'
   HomeKit Bridge                  Blind stopping 'HomeKit Bridge'
   HomeKit Bridge                  Blind stopping 'Motion Sensor Bridge'
   HomeKit Bridge                  Blind stopping 'Security Cameras Bridge'
   Stopped plugin HomeKit Bridge
   Upgrading plugin HomeKit Bridge to newer version 0.20.0 (previous version moved to trash)
   Loading plugin "HomeKit Bridge 0.20.0"
   Starting plugin "HomeKit Bridge 0.20.0" (pid 96061)
   Started plugin "HomeKit Bridge 0.20.0"
   HomeKit Bridge                  Upgrading plugin from 0.19.9 to 0.20.0
   HomeKit Bridge                  Upgrading Environmental Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrading HomeKit Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrading Motion Sensor Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrading Security Cameras Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrade success
   HomeKit Bridge                  Attempting to start 'Environmental Bridge'
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Security Cameras Bridge'.
   HomeKit Bridge                  Attempting to start 'HomeKit Bridge'
   HomeKit Bridge                  Attempting to start 'Motion Sensor Bridge'
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Security Cameras Bridge'.
   HomeKit Bridge                  Attempting to start 'Security Cameras Bridge'
   HomeKit Bridge                  HomeKit Bridge is loaded and ready to use
   HomeKit Bridge                  Server 'Security Cameras Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge                  Server 'Motion Sensor Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge                  Server 'Environmental Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge                  Server 'HomeKit Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory

**Comment by Colorado4Wheeler** [comment]
That reads like the SecuritySpy server was unreachable and that caused the server device to not populate fields.  My SS plugin goes offline often.  I would have to trap that part of the code.  Nothing changed in that code block between updates so it’s not new code causing the issue.

**Comment by grwilde** [comment]
I believe this error message has appeared in several previous upgrades as well, but I did not capture it. It may well be an erroneous error message because everything appears to work correctly after the upgrade. The correct username and password must be passed correctly from SecuritySpy to HomeKit Bridge or I assume the cameras would not be refreshed properly in the Home App. The only devices I have in my Security Cameras Bridge Server are my two SecuritySpy cameras. All of my numerous other devices are in my three other servers which all restarted correctly without any error messages.

**Comment by Colorado4Wheeler** [comment]
The reason it works is because when it hits that error it stops trying to write the config.json, so it’s likely that you are running off your original.  Is it possible you have a 2nd SS server in Indigo?

**Comment by grwilde** [comment]
I do have two SecuritySpy devices (cameras) in Indigo, but as far as I know there is only one SecuritySpy server. It would not be the first time that multiple processes showed up on my Mac, but I do not see anything in the Activity Monitor that shows two SS servers running. I do recall that when I first set up the HomeKit Bridge server for my cameras I encountered some problems. So I deleted the camera server and set up a new one with no problem. Could it be that there are some remnants of this earlier one still around that is causing the error? In any event this is a very minor anomaly since it only occurs when restarting the server and does not affect the use of your wonderful plugin.

**Comment by grwilde** [comment]
You were right that the config.json file for the camera server was not updated yesterday, whereas the other 3 were. Here is the last update from the config.json file:
"HomeKit configuration generated by HomeKit Bridge on 2018-03-18 00:41:28.336000 for device Security Cameras Bridge"

**Comment by Colorado4Wheeler** [comment]
Are all of your cameras on the 'Motion Sensor Bridge' server?  Try adding them to another server, just to see what happens.  You can still leave them where they are but add duplicates on a new device and see if that also errors out. 

The flow of this SecuritySpy integration is this:

- You select a SS camera
- The plugin reads the SS camera to determine the Indigo SS server device
- The plugin reads the SS server device on Indigo to derive the IP address 
- We query the SS server directly from the IP address to get the additional parameters we need

You are breaking at step 3 so that indicates that either the server device that your SS camera is referring to is no longer there or if it's there it doesn't have an IP address in its states.  That's pretty much the only way you could get the message you got.

**Comment by Colorado4Wheeler** [comment]
If you cannot find the missing piece then run the following code in an action group script using the Indigo ID for the SS server and then again for one of the SS cameras that aren't working with the plugin so I can see if states are missing. 

	server = indigo.devices[SS_SERVER_ID]
	camera = indigo.devices[SS_CAMERA_ID]

	indigo.server.log (u"Server Device ID {}".format(server.id))
	indigo.server.log(unicode(server.states))
	indigo.server.log (u"Camera Device ID {}".format(camera.id))
	indigo.server.log(unicode(camera.states))

Be sure to edit the output to take out any usernames and passwords that are in there, but just replace them with "***" or something to let me know they actually HAD them.

**Comment by grwilde** [comment]
I notice that my Motion Sensor Bridge also has in its Persist Preferences folder two accessories for the two cameras that are not being used. My Camera Bridge also has in its Persist Preferences folder the two accessories for the two cameras that are currently being used. Perhaps this is causing the problem since the Motion Sensor Bridge does not have any camera information in its config.json file.

**Comment by grwilde** [comment]
All of my cameras are now in the Security Cameras Bridge Server and not in the Motion Sensors Bridge Server. I believe I originally had the cameras on my Motion Sensors Bridge Server, but deleted them because I wanted a separate server just for the cameras. I deleted the cameras in the Configuration Settings of the server. This may have left behind the extra files I noted previously in the server preferences.

This is the result of running the action group script (I added both cameras to the script):

Script                          Server Device ID 1418254634
   Script                          States : (dict)
     state : ready (string)
     state.preparing : false (bool)
     state.ready : true (bool)
     state.unavailable : false (bool)
     version : 4.2.3 (string)
   Script                          Camera Device ID 1792078598
   Script                          States : (dict)
     actions : on (on/off bool)
     motion : on (on/off bool)
     recording : on (on/off bool)
     sensitivity : 50 (integer)
     state : active (string)
     state.active : true (bool)
     state.disconnected : false (bool)
     state.passive : false (bool)
     state.preparing : false (bool)
     state.unavailable : false (bool)
     type : Network Axis (older MPEG-4 cameras) (string)
   Script                          Camera Device ID 270173689
   Script                          States : (dict)
     actions : on (on/off bool)
     motion : on (on/off bool)
     recording : on (on/off bool)
     sensitivity : 50 (integer)
     state : active (string)
     state.active : true (bool)
     state.disconnected : false (bool)
     state.passive : false (bool)
     state.preparing : false (bool)
     state.unavailable : false (bool)
     type : Network Amcrest (string)

**Comment by grwilde** [comment]
I set up a new Test Server and added only the two SecuritySpy Cameras - but got the same error:

Mar 22, 2018 at 7:24:49 PM
   HomeKit Bridge Error            Exception in homekit.getStashRecordForObject line 884: ('key includedDevices not found in dict', u'Server Id: 1890280422', u'Server data: com.eps.indigoplugin.homekit-bridge : (dict)')
							 CODE: includedDevices = json.loads(serverProps["includedDevices"])

   HomeKit Bridge Error            Exception in homekit.getStashRecordForObject line 884: ('key includedDevices not found in dict', u'Server Id: 1890280422', u'Server data: com.eps.indigoplugin.homekit-bridge : (dict)')
							 CODE: includedDevices = json.loads(serverProps["includedDevices"])

      HomeKit Bridge Error            Exception in homekit.getStashRecordForObject line 884: ('key includedDevices not found in dict', u'Server Id: 1890280422', u'Server data: com.eps.indigoplugin.homekit-bridge : (dict)')
							 CODE: includedDevices = json.loads(serverProps["includedDevices"])


   HomeKit Bridge Error            Exception in homekit.getStashRecordForObject line 884: ('key includedDevices not found in dict', u'Server Id: 1890280422', u'Server data: com.eps.indigoplugin.homekit-bridge : (dict)')
							 CODE: includedDevices = json.loads(serverProps["includedDevices"])

   HomeKit Bridge                  Server 'Test Server' has changed ports or users, validating config
   HomeKit Bridge                  NEW DEVICE
   SQL Logger                      adding column "onoffstate_ui" to table device_history_1890280422 ("Test Server")
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Test Server'.
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Test Server'.
   HomeKit Bridge                  Attempting to start 'Test Server'


   HomeKit Bridge Error            HomeKit server 'Test Server' could not be started, please check the service logs for more information,
now issuing a forced shutdown of the service to be safe.

If you continue to have problems starting this server use the Advanced Plugin Actions menu option to rebuild the Homebridge folder.
Instructions at https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#rebuild-homebridge-folder

**Comment by Colorado4Wheeler** [comment]
I don't know, you suddenly and without explanation are having one problem after another and I really am having trouble keeping up with it or coming up with ideas for why that may be happening.  

I cannot even being to diagnose why you are getting the includedDevice message, particularly if you added two security cameras, because the data for those security cameras is stored IN includedDevices, if that wasn't present you wouldn't even see them on the list.  Not to mention the fact that there must be at least 5 safeguards to ensure includedDevices is in the props even if you **don't** have any devices.

I would say if you get that message then run the following script so I can see how it's even possible that you don't have that field.  Also let me know precisely when that message occurs, is it while you are in the UI or after?  When you try to start the server or when you save the config?

	indigo.server.log(unicode(indigo.devices[SERVER_ID]))

As for the SecuritySpy issue, that output didn't have an IP address so try using this script instead:

	server = indigo.devices[SS_SERVER_ID]
	camera = indigo.devices[SS_CAMERA_ID]

	indigo.server.log (u"Server Device ID {}".format(server.id))
	indigo.server.log(unicode(server))
	indigo.server.log (u"Camera Device ID {}".format(camera.id))
	indigo.server.log(unicode(camera.states))

**Comment by grwilde** [comment]
Here are the results of the SecuritySpy script (actual usernames and passwords deleted):

   Action Group                    SecuritySpy Camera Test
   Script                          Server Device ID 1418254634
   Script                          address : localhost:8002
batteryLevel : None
buttonGroupCount : 0
configured : True
description : SecuritySpy
deviceTypeId : server
displayStateId : state
displayStateImageSel : None
displayStateValRaw : ready
displayStateValUi : ready
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1302595955
globalProps : MetaProps : (dict)
     org.cynic.indigo.securityspy : (dict)
          address : localhost:8002 (string)
          errors : false (bool)
          password : "***" (string)
          port : 8002 (string)
          username : "***" (string)
          xaddress :  (string)
id : 1418254634
lastChanged : 2018-03-22 02:24:24
lastSuccessfulComm : 2018-03-22 02:24:24
model : Server
name : SecuritySpy Web Server
ownerProps : org.cynic.indigo.securityspy : (dict)
     address : localhost:8002 (string)
     errors : false (bool)
     password : "***" (string)
     port : 8002 (string)
     username : "***" (string)
     xaddress :  (string)
pluginId : org.cynic.indigo.securityspy
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     state : ready (string)
     state.preparing : false (bool)
     state.ready : true (bool)
     state.unavailable : false (bool)
     version : 4.2.3 (string)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None
   Script                          Camera Device ID 1792078598
   Script                          States : (dict)
     actions : on (on/off bool)
     motion : on (on/off bool)
     recording : on (on/off bool)
     sensitivity : 50 (integer)
     state : active (string)
     state.active : true (bool)
     state.disconnected : false (bool)
     state.passive : false (bool)
     state.preparing : false (bool)
     state.unavailable : false (bool)
     type : Network Axis (older MPEG-4 cameras) (string)
   Script                          Camera Device ID 270173689
   Script                          States : (dict)
     actions : on (on/off bool)
     motion : on (on/off bool)
     recording : on (on/off bool)
     sensitivity : 50 (integer)
     state : active (string)
     state.active : true (bool)
     state.disconnected : false (bool)
     state.passive : false (bool)
     state.preparing : false (bool)
     state.unavailable : false (bool)
     type : Network Amcrest (string)

**Comment by grwilde** [comment]
I set up a new  camera server. It initially had only a default lamp module because I did not add any devices. When saved it showed no errors and the server started OK. I then went back and added a single camera to the server device and deleted the default lamp module. When I saved this device from the dialog I got the following error:

Mar 23, 2018 at 12:58:04 PM
 HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'New Camera Server'.
   HomeKit Bridge                  Attempting to stop 'New Camera Server'
   HomeKit Bridge                  HomeKit server 'New Camera Server' has been stopped
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4616: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'New Camera Server'.
   HomeKit Bridge                  Attempting to start 'New Camera Server'
   HomeKit Bridge                  Server 'New Camera Server' has successfully started, you can use your HomeKit apps or Siri for this accessory

The server did start even with these errors and is running. The following is the script you asked me to run:

   Action Group                    HomeKit Bridge Test
   Script                          address : 031-45-154 | 51830
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : Server
displayStateId : onOffState
displayStateImageSel : SensorOn
displayStateValRaw : True
displayStateValUi : Running
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 0
globalProps : MetaProps : (dict)
     com.eps.indigoplugin.homekit-bridge : (dict)
          SupportsStatusRequest : false (bool)
          accessoryNamePrefix :  (string)
          action :  (string)
          address : 031-45-154 | 51830 (string)
          alias :  (string)
          autoStartStop : true (bool)
          bitrate : 300 (string)
          camHeight : 720 (string)
          camWidth : 1280 (string)
          configOption : include (string)
          device :  (string)
          deviceLimitReached : false (bool)
          deviceList : (list)
               Item : 270173689 (string)
          deviceOrActionSelected : false (bool)
          editActive : false (bool)
          enableOnOffInvert : false (bool)
          excludedActions : [] (string)
          excludedDevices : [] (string)
          firmwareValue : indigoVersion (string)
          fps : 30 (string)
          hkType : service_CameraRTPStreamManagement (string)
          homeKitTypeEnabled : true (bool)
          includedActions : [] (string)
          includedDevices : [{"jkey": "ffe093c3d73823b875e2aa9efd3ef249baa6c1373b56499ebcc116e19298bb27", "name": "Driveway Camera", "url": "", "invert": false, "object": "Device", "complex": false, "id": 270173689, "char": [], "alias": "Driveway Camera", "api": false, "link": [], "action": [], "apilock": false, "tempIsF": false, "type": "", "hktype": "service_CameraRTPStreamManagement"}] (string)
          invertOnOff : false (bool)
          isAPIDevice : false (bool)
          isFahrenheit : false (bool)
          isFahrenheitEnabled : false (bool)
          listSort : sortbyname (string)
          listenPort : 8449 (string)
          maxStreams : 2 (string)
          modelValue : indigoModelSubmodel (string)
          objectAction : add (string)
          objectType : device (string)
          packet : 1316 (string)
          pin : 031-45-154 (string)
          port : 51830 (string)
          serverOverride : false (bool)
          showEditArea : true (bool)
          stillURL : -i http:// (string)
          tempunits : f (string)
          username : CC:22:3D:E3:CE:14 (string)
          videoURL : -re -i http:// (string)
id : 141276609
lastChanged : 2018-03-23 12:58:54
lastSuccessfulComm : 2018-03-23 12:58:54
ledStates : []
model : HomeKit Accessory Server
name : New Camera Server
onState : True
ownerProps : com.eps.indigoplugin.homekit-bridge : (dict)
     SupportsStatusRequest : false (bool)
     accessoryNamePrefix :  (string)
     action :  (string)
     address : 031-45-154 | 51830 (string)
     alias :  (string)
     autoStartStop : true (bool)
     bitrate : 300 (string)
     camHeight : 720 (string)
     camWidth : 1280 (string)
     configOption : include (string)
     device :  (string)
     deviceLimitReached : false (bool)
     deviceList : (list)
          Item : 270173689 (string)
     deviceOrActionSelected : false (bool)
     editActive : false (bool)
     enableOnOffInvert : false (bool)
     excludedActions : [] (string)
     excludedDevices : [] (string)
     firmwareValue : indigoVersion (string)
     fps : 30 (string)
     hkType : service_CameraRTPStreamManagement (string)
     homeKitTypeEnabled : true (bool)
     includedActions : [] (string)
     includedDevices : [{"jkey": "ffe093c3d73823b875e2aa9efd3ef249baa6c1373b56499ebcc116e19298bb27", "name": "Driveway Camera", "url": "", "invert": false, "object": "Device", "complex": false, "id": 270173689, "char": [], "alias": "Driveway Camera", "api": false, "link": [], "action": [], "apilock": false, "tempIsF": false, "type": "", "hktype": "service_CameraRTPStreamManagement"}] (string)
     invertOnOff : false (bool)
     isAPIDevice : false (bool)
     isFahrenheit : false (bool)
     isFahrenheitEnabled : false (bool)
     listSort : sortbyname (string)
     listenPort : 8449 (string)
     maxStreams : 2 (string)
     modelValue : indigoModelSubmodel (string)
     objectAction : add (string)
     objectType : device (string)
     packet : 1316 (string)
     pin : 031-45-154 (string)
     port : 51830 (string)
     serverOverride : false (bool)
     showEditArea : true (bool)
     stillURL : -i http:// (string)
     tempunits : f (string)
     username : CC:22:3D:E3:CE:14 (string)
     videoURL : -re -i http:// (string)
pluginId : com.eps.indigoplugin.homekit-bridge
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
states : States : (dict)
     onOffState : on (on/off bool)
     onOffState.ui : Running (string)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None

**Comment by grwilde** [comment]
The new camera server does not show the camera in the Home App - only the new Bridge. The config.json file also does not have the camera - only the bridge.  So even though the server is running there is no camera.

**Comment by Colorado4Wheeler** [comment]
I honestly wouldn’t expect it to show in the config.json if you are getting errors during the configuration creation process.

**Comment by Colorado4Wheeler** [comment]
What is your Indigo forum ID?

**Comment by grwilde** [comment]
My Indigo forum ID is GRWilde

**Comment by Colorado4Wheeler** [comment]
What version of SS are you running?

**Comment by Colorado4Wheeler** [comment]
I see the problem clearly, I'm just wondering why it's not populated as mine is.  You say that everything worked before and wrote the cameras and then suddenly stopped.  The one thing that changed between it working and not was me getting the extra characteristics from the SS server and I see very clearly now that the field on your config is empty, if it wasn't you most certainly would not be getting errors.

**Comment by Colorado4Wheeler** [comment]
I mean to ask what version of SS and of the SS plugin - I wonder if that's the difference between yours and mine.  I can fix it in code now that I see the problem but want to know why it's like that in the first place.

**Comment by Colorado4Wheeler** [comment]
I'm still interested in the version info but I've added some extra code to work around this issue in the next release.  That release MAY be today if I can put the current development tasks in complications in a state that won't break the plugin since it's only 1/2 implemented right now.  If not then hopefully by the end of the weekend.

**Comment by grwilde** [comment]
My version of SecuritySpy is 4.2.3 and my version of the plugin is 2.3.0

My previously set up cameras still work in the Home App (just not those in the new server) and the old camera server still has an old config.json file dated March 18th.

**Comment by Colorado4Wheeler** [comment]
Yea, it’s because the ‘xaddress’ is empty in your SS config.  I’ll see if that’s a difference between versions - although you’re the only one reporting it so I suspect that it may be you are on a slightly different version than the rest of us are, but regardless it’s already patched for the next release.

**Comment by Colorado4Wheeler** [comment]
Try the latest release, that should resolve your issue.  Please let me know if it does not.

**Comment by grwilde** [comment]
Still getting an error:

   Stopping plugin HomeKit Bridge (pid 1598)
   HomeKit Bridge Warning          

#####################################################################
# HOMEKIT BRIDGE RUNNING SERVER SHUTDOWN                            #
#####################################################################
# Now blind stopping all running servers, due to Indigo timeout     #
# limits the plugin cannot wait for them to stop but will instead   #
# shut them down blindly and let them refresh when the plugin       #
# restarts                                                          #
#####################################################################

   HomeKit Bridge                  Blind stopping 'Environmental Bridge'
   HomeKit Bridge                  Blind stopping 'HomeKit Bridge'
   HomeKit Bridge                  Blind stopping 'Motion Sensor Bridge'
   HomeKit Bridge                  Blind stopping 'Security Cameras Bridge'
   Stopped plugin HomeKit Bridge
   Upgrading plugin HomeKit Bridge to newer version 0.20.1 (previous version moved to trash)
   Loading plugin "HomeKit Bridge 0.20.1"
   Starting plugin "HomeKit Bridge 0.20.1" (pid 44141)
   Started plugin "HomeKit Bridge 0.20.1"
   HomeKit Bridge                  Upgrading plugin from 0.20.0 to 0.20.1
   HomeKit Bridge                  Upgrading Environmental Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrading HomeKit Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrading Motion Sensor Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrading Security Cameras Bridge for changes in this plugin release
   HomeKit Bridge                  Upgrade success
   HomeKit Bridge                  Attempting to start 'Environmental Bridge'
   HomeKit Bridge                  Attempting to start 'HomeKit Bridge'
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4607: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Security Cameras Bridge'.
   HomeKit Bridge                  Attempting to start 'Motion Sensor Bridge'
   HomeKit Bridge Error            Exception in plugin.buildServerConfigurationDict line 4607: Invalid URL u'http://:8002/++systemInfo': No host supplied
							 CODE: data = requests.get(ssSystem, auth=(ssServer.ownerProps["username"], ssServer.ownerProps["password"])).content

   HomeKit Bridge Error            Unable to build server configuration for 'Security Cameras Bridge'.
   HomeKit Bridge                  Attempting to start 'Security Cameras Bridge'
   HomeKit Bridge Warning          Unable to set the value of ContactSensorState on Bay Alarm Event to false because that attribute requires int and it was given unicode
   HomeKit Bridge                  HomeKit Bridge is loaded and ready to use
   HomeKit Bridge                  Server 'Security Cameras Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge Warning          Unable to set the value of ContactSensorState on Garage Door Status to false because that attribute requires int and it was given unicode
   HomeKit Bridge                  Server 'Motion Sensor Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge                  Server 'Environmental Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory
   HomeKit Bridge                  Server 'HomeKit Bridge' has successfully started, you can use your HomeKit apps or Siri for this accessory

**Comment by Colorado4Wheeler** [comment]
Ok, I know what I missed.  I’ll have another update tomorrow.

**Comment by Colorado4Wheeler** [comment]
Ok, I rewrote the entire authentication for SecuritySpy, let's see if this works.  I'm doing this blindly because I don't have this issue on my end so hopefully this is the one that does the trick.
