### ISSUE TITLE
Intermittently stops updating status

### ISSUE THREAD

**Issue by durosity** [Colorado4Wheeler/HomeKit-Bridge#85]
I’ve noticed the last couple of days (I think since v.20 appeared) that occasionally the status of devices for all servers will stop updating.  Eg If the temperature increases in the living room or a light gets switched on.  Performing an action in Home app still has the desired effect, and if I change the set point on a thermostat after a moment or two the current temperature will update to the correct one.. but without any actual interaction Homekit seems to just stall updating.  Now this has only happened 3-4 times, but it’s definitely affecting only HBK devices (as my Hue ones still report correctly) and fixing it seems to have worked by either force quitting the home app, changing a setting in Home, or resetting the HKB plugin.  Assuming it recurs is there anything you’d recommend I try or try to capture that may help identify this gremlin?  (Really sorry to drop this one on you.. I don’t wanna overload you on it.. please don’t hurt me!!)

**Comment by Colorado4Wheeler** [comment]
What kind of thermostat?  Nest by chance?

**Comment by durosity** [comment]
Nope it’s the Smart Devices plugin that simulates a thermostat.  But I have to stress it’s not just that, its ALL devices status.. eg motion sensors, lights, door locks.. It’s like the plugin stops feeding HomeKit updated information from indigo.

**Comment by durosity** [comment]
Will do!  I appreciate how awkward it can be to identify where this kinda intermittent issue is coming from.  Where I work a few years ago we had an issue with a critical file in the DB blanking itself randomly.. took weeks to find out it was caused by loading an activity window then closing it before it’d fully populated.  That was a whole set of teams of testers, programmers and support technicians working all day every day to try and replicate it!

**Comment by Colorado4Wheeler** [comment]
Since there's been no movement on this in 24 days I'm closing it.  There are actions now in HKB to restart one or all servers when needed in case you need to do that.
