### ISSUE TITLE
Camera server now adds cameras but does not load

### ISSUE THREAD

**Issue by durosity** [Colorado4Wheeler/HomeKit-Bridge#92]
With beta 22 adding a server device with cameras configured in HKB will also add the camera devices at the same time linked to that server, but they won’t load - going to add accessory will show an additional camera to add for each one that doesn’t seem to be linked to the bridge device (as it used to be) and they load but this results in 2 devices for each camera, one that loads but isn’t linked to bridge and one that doesn’t load but is linked to bridge.

**Comment by Colorado4Wheeler** [comment]
Wow, I'm not even sure what you mean.  Nothing changed with cameras, it's identical to the way it was in 0.21.  Mine is working fine so I don't really have a frame of reference for whatever the issue really is.

**Comment by Colorado4Wheeler** [comment]
Disable the enhancements, I’ll patch tomorrow.  I know the problem.

**Comment by Colorado4Wheeler** [comment]
I think this is the same as #94 so it should be fixed in the next revision.

**Comment by durosity** [comment]
Just to clarify then if I have a server device setup with nothing but cameras on it it shouldnt have any accessories and the cameras themselves have to be added manually one at a time?  

(And sorry the original post probably made little sense.  I was trying to post it when I had no time to do it right and was distracted by something else).
