### ISSUE TITLE
Optimization: POST instead of GET to /devices/ID

### ISSUE THREAD

**Issue by webdeck** [Colorado4Wheeler/HomeKit-Bridge#93]
Right now, a GET to /devices/_ID_ on homebridge-indigo2 will result in a getInfo request back to HKB.

Instead, you could send a POST to /devices/_ID_ with the updated values directly, to avoid the call back to HKB.

Details:

POST to /devices/_ID_
Include header:  `Content-Type: application/json`
POST data is the same JSON data you return in a getInfo request

If I am unable to parse the POST data, I will treat it the same as a GET request and call getInfo.

**Comment by webdeck** [comment]
Note that you will need a new version of homebridge-indigo2 to support this.  You can add it for now since the POST does the same thing as the GET in the current version you have.

**Comment by Colorado4Wheeler** [comment]
Excellent, I'll work on that, thanks.

**Comment by Colorado4Wheeler** [comment]
This is done and in the next release.
