### ISSUE TITLE
Temperature Sensor Reads 32 deg F in HomeKit

### ISSUE THREAD

**Issue by dekillmer** [Colorado4Wheeler/HomeKit-Bridge#95]
Hi, there. All of my RFXCOM temperature sensors are reading 32 deg F in HomeKit. I sure appreciate all your work and this is the only thing that is not working for me!

Thanks,
Dennis

	Apr 6, 2018 at 8:38:25 PM
	   HomeKit Bridge                  Simulating HomeKit values for Sauna Room Temperature
	   HomeKit Bridge                  ##### DEVICE DATA DUMP #####
	   HomeKit Bridge                  address : 1087
	batteryLevel : None
	buttonGroupCount : 0
	configured : True
	description : 
	deviceTypeId : Temperature
	displayStateId : display
	displayStateImageSel : TemperatureSensorOn
	displayStateValRaw : 54.9 °F
	displayStateValUi : 54.9 °F
	enabled : True
	energyAccumBaseTime : None
	energyAccumTimeDelta : None
	energyAccumTotal : None
	energyCurLevel : None
	errorState : 
	folderId : 39395952
	globalProps : MetaProps : (dict)
		 nl.rjdekok.indigoplugin.RFXCOM : (dict)
			  MultiplyBatteryLevel : false (bool)
			  SupportsOnState : false (bool)
			  SupportsSensorValue : true (bool)
			  SupportsStatusRequest : false (bool)
			  address : 1087 (string)
			  displayField : Temp (string)
			  sensorNumber : 1087 (string)
			  sensorValueType : Temp (string)
			  subModel : Temperature (string)
	id : 1619368353
	lastChanged : 2018-04-06 20:37:48
	lastSuccessfulComm : 2018-04-06 20:37:48
	model : Temperature Sensor
	name : Sauna Room Temperature
	ownerProps : nl.rjdekok.indigoplugin.RFXCOM : (dict)
		 MultiplyBatteryLevel : false (bool)
		 SupportsOnState : false (bool)
		 SupportsSensorValue : true (bool)
		 SupportsStatusRequest : false (bool)
		 address : 1087 (string)
		 displayField : Temp (string)
		 sensorNumber : 1087 (string)
		 sensorValueType : Temp (string)
		 subModel : Temperature (string)
	pluginId : nl.rjdekok.indigoplugin.RFXCOM
	pluginProps : com.eps.indigoplugin.homekit-bridge : (dict)
	protocol : Plugin
	remoteDisplay : True
	states : States : (dict)
		 batteryLevel : 10 (integer)
		 display : 54.9 °F (string)
		 display.ui : 54.9 °F (string)
		 humidity : 0 (integer)
		 humidityStatus :  (string)
		 lastUpdated : 2018/04/06 20:37:48 (string)
		 maxYesterdayhumidity : 0 (integer)
		 maxYesterdaytemperature : 55.4 (real)
		 maxhumidity : 0 (integer)
		 maxtemperature : 56.3 (real)
		 minYesterdayhumidity : 0 (integer)
		 minYesterdaytemperature : 54.0 (real)
		 minhumidity : 0 (integer)
		 mintemperature : 53.8 (real)
		 signalStrength : 6 (integer)
		 temperature : 54.9 (real)
		 temperature.ui : 54.9 °F (string)
		 type : 2 (integer)
	subModel : 
	supportsAllLightsOnOff : False
	supportsAllOff : False
	supportsStatusRequest : False
	version : None
	   HomeKit Bridge                  ##### DEVICE SIMULATION DATA #####
	   HomeKit Bridge                  Service : 
		alias : Sauna Room Temperature
		model : 
		subModel : 
		indigoType : indigo.Device
		pluginType : indigo.Device.nl.rjdekok.indigoplugin.RFXCOM.Temperature
		type : TemperatureSensor
		desc : Temperature Sensor
		objId : 1619368353
		serverId : 1461499361
		invertOnState : False
		convertFahrenheit : True
		required : (List)
			CurrentTemperature : 0.0
		optional : (List)
			StatusActive
			StatusFault
			StatusTampered
			Name
			StatusLowBattery : 0
		native : True
		requiresPlugin : (List)
		actions : (List)
		loadOptional : False
		characterDict : (Dict)
			CurrentTemperature : 0.0

	****

**Comment by Colorado4Wheeler** [comment]
There's no direct support for that plugin at the moment, I'll add it to the list but it may be a minute before it gets integrated.

**Comment by dekillmer** [comment]
Thank you!

**Comment by Colorado4Wheeler** [comment]
This is supported in the next 1.0.2 release (after the current beta 3)
